export const GAME_CARD_DEFS = [
  {
    href: "/kuis",
    titleKey: "cardQuizTitle" as const,
    descKey: "cardQuizDesc" as const,
    bg: "from-yellow-300 to-orange-400",
    emoji: "⭐",
  },
  {
    href: "/cocokkan",
    titleKey: "cardMatchTitle" as const,
    descKey: "cardMatchDesc" as const,
    bg: "from-emerald-300 to-teal-400",
    emoji: "🎯",
  },
  {
    href: "/tebak-ayat",
    titleKey: "cardGuessTitle" as const,
    descKey: "cardGuessDesc" as const,
    bg: "from-violet-300 to-fuchsia-400",
    emoji: "🔢",
  },
  {
    href: "/sambung",
    titleKey: "cardConnectTitle" as const,
    descKey: "cardConnectDesc" as const,
    bg: "from-orange-300 to-rose-400",
    emoji: "🔗",
  },
  {
    href: "/ular-tangga",
    titleKey: "cardSnakeLadderTitle" as const,
    descKey: "cardSnakeLadderDesc" as const,
    bg: "from-lime-300 to-emerald-400",
    emoji: "🎲",
  },
  {
    href: "/berkebun",
    titleKey: "cardFarmingTitle" as const,
    descKey: "cardFarmingDesc" as const,
    bg: "from-green-400 to-lime-600",
    emoji: "🌾",
  },
  {
    href: "/tukang-burger",
    titleKey: "cardBurgerTitle" as const,
    descKey: "cardBurgerDesc" as const,
    bg: "from-amber-400 to-orange-600",
    emoji: "🍔",
  },
] as const;
