// Theme registry. Each theme is one character with its own pastel palette.
// The actual character artwork is *not* generated by this app — you drop your
// own image file at `imageSrc` (see `public/characters/README.md`). When the
// file is missing, the picker shows a neutral coloured circle with the
// character's initial as a placeholder.

export interface ThemePalette {
  /** Strong primary color — used for nav highlights and accents. */
  primary: string;
  /** Darker variant for borders / deep text. */
  primaryDeep: string;
  /** Very soft tint for backgrounds and placeholder fills. */
  primarySoft: string;
  /** Secondary accent. */
  accent: string;
  /** Three radial gradient stops painted onto <body>. */
  bgStops: [string, string, string];
  /** Solid background base behind the gradients. */
  bgBase: string;
}

export interface ThemeDef {
  id: string;
  /** Display name. */
  name: string;
  /** Short, kid-friendly tagline. */
  tagline: string;
  /**
   * Path to the character image (e.g. a PNG/SVG you dropped into
   * `public/characters/`). When the file is missing the app shows a neutral
   * coloured placeholder — no generated character art.
   */
  imageSrc?: string;
  palette: ThemePalette;
}

export const THEMES: readonly ThemeDef[] = [
  {
    id: "kitty",
    name: "Hello Kitty",
    tagline: "Si kucing pink yang lucu",
    imageSrc: "/characters/kitty.png",
    palette: {
      primary: "#ff7eb6",
      primaryDeep: "#db2777",
      primarySoft: "#ffd6e7",
      accent: "#ff5e9c",
      bgStops: ["#ffe4f0", "#d8ecff", "#fff5b8"],
      bgBase: "#fff1f7",
    },
  },
  {
    id: "melody",
    name: "My Melody",
    tagline: "Kelinci manis bertudung pink",
    imageSrc: "/characters/melody.png",
    palette: {
      primary: "#f9728c",
      primaryDeep: "#be185d",
      primarySoft: "#ffd9e1",
      accent: "#ef4f7b",
      bgStops: ["#ffe4ec", "#ffd2dc", "#fff1d6"],
      bgBase: "#fff0f4",
    },
  },
  {
    id: "kuromi",
    name: "Kuromi",
    tagline: "Si ungu nakal, super keren",
    imageSrc: "/characters/kuromi.png",
    palette: {
      primary: "#8b5cf6",
      primaryDeep: "#6d28d9",
      primarySoft: "#e9defc",
      accent: "#ec4899",
      bgStops: ["#e9defc", "#fde4f3", "#dfd0ff"],
      bgBase: "#f4eefe",
    },
  },
  {
    id: "cinnamon",
    name: "Cinnamoroll",
    tagline: "Anjing putih bertelinga panjang",
    imageSrc: "/characters/cinnamon.png",
    palette: {
      primary: "#38bdf8",
      primaryDeep: "#0284c7",
      primarySoft: "#d1efff",
      accent: "#7dd3fc",
      bgStops: ["#dcefff", "#fef9c3", "#ffffff"],
      bgBase: "#eff8ff",
    },
  },
  {
    id: "pompom",
    name: "Pompompurin",
    tagline: "Si kuning hangat bertopi cokelat",
    imageSrc: "/characters/pompom.png",
    palette: {
      primary: "#f59e0b",
      primaryDeep: "#b45309",
      primarySoft: "#fef3c7",
      accent: "#fbbf24",
      bgStops: ["#fff3a3", "#ffe8c2", "#ffe4d6"],
      bgBase: "#fff8e1",
    },
  },
  {
    id: "keroppi",
    name: "Keroppi",
    tagline: "Si katak hijau ceria",
    imageSrc: "/characters/keroppi.png",
    palette: {
      primary: "#10b981",
      primaryDeep: "#047857",
      primarySoft: "#d1fae5",
      accent: "#34d399",
      bgStops: ["#d1fae5", "#fde68a", "#dcfce7"],
      bgBase: "#ecfdf5",
    },
  },
  {
    id: "pekkle",
    name: "Pekkle",
    tagline: "Bebek putih bercelemek biru",
    imageSrc: "/characters/pekkle.png",
    palette: {
      primary: "#2563eb",
      primaryDeep: "#1e40af",
      primarySoft: "#dbeafe",
      accent: "#fbbf24",
      bgStops: ["#dbeafe", "#fef3c7", "#ffffff"],
      bgBase: "#eff6ff",
    },
  },
  {
    id: "badtz",
    name: "Bad Badtz-Maru",
    tagline: "Pinguin hitam yang seru",
    imageSrc: "/characters/badtz.png",
    palette: {
      primary: "#475569",
      primaryDeep: "#1e293b",
      primarySoft: "#e2e8f0",
      accent: "#fbbf24",
      bgStops: ["#fef3c7", "#fce7f3", "#e2e8f0"],
      bgBase: "#f8fafc",
    },
  },
  {
    id: "hangyodon",
    name: "Hangyodon",
    tagline: "Si biru malu-malu dari laut",
    imageSrc: "/characters/hangyodon.png",
    palette: {
      primary: "#14b8a6",
      primaryDeep: "#0f766e",
      primarySoft: "#ccfbf1",
      accent: "#fb7185",
      bgStops: ["#ccfbf1", "#fed7aa", "#cffafe"],
      bgBase: "#f0fdfa",
    },
  },
  {
    id: "gudetama",
    name: "Gudetama",
    tagline: "Telur kuning paling santai",
    imageSrc: "/characters/gudetama.png",
    palette: {
      primary: "#eab308",
      primaryDeep: "#854d0e",
      primarySoft: "#fef9c3",
      accent: "#fde68a",
      bgStops: ["#fef9c3", "#fffbeb", "#ffffff"],
      bgBase: "#fefce8",
    },
  },
] as const;

export const DEFAULT_THEME_ID = "kitty";

export function getTheme(id: string | null | undefined): ThemeDef {
  if (!id) return THEMES[0];
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}

export function isThemeId(value: unknown): value is ThemeDef["id"] {
  return typeof value === "string" && THEMES.some((t) => t.id === value);
}
