import type { ThemeDef } from "@/lib/themes";

interface MascotImageProps {
  size?: number;
  /** Accepted for API compatibility; ignored — static images don't have moods. */
  mood?: "happy" | "excited" | "sad" | "thinking";
  className?: string;
  theme: ThemeDef;
}

/**
 * Renders a theme's character image (e.g. the file you dropped into
 * `public/characters/`). Below the image sits a neutral placeholder — a
 * coloured circle with the character's initial — so:
 *
 *   - When the image file exists, it paints fully on top of the placeholder.
 *   - When the file is missing or 404s, the browser paints nothing for the
 *     overlay (no broken-image icon) and the placeholder shows through.
 *
 * No SVG character art is generated by the app; only files you supply.
 */
export function MascotImage({
  size = 96,
  className = "",
  theme,
}: MascotImageProps) {
  const initial = theme.name.charAt(0).toUpperCase();
  return (
    <div
      className={`relative inline-block overflow-hidden rounded-full ring-2 ${className}`}
      style={{
        width: size,
        height: size,
        backgroundColor: theme.palette.primarySoft,
        borderColor: theme.palette.primary,
      }}
    >
      <div
        className="absolute inset-0 flex items-center justify-center font-extrabold"
        style={{
          color: theme.palette.primaryDeep,
          fontSize: size * 0.42,
          lineHeight: 1,
        }}
        aria-hidden="true"
      >
        {initial}
      </div>
      {theme.imageSrc && (
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            backgroundImage: `url(${theme.imageSrc})`,
            backgroundSize: "contain",
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center",
          }}
          aria-hidden="true"
        />
      )}
    </div>
  );
}
