// Pre-fetches juz 30 (surah 78–114) Arabic + Indonesian text from
// fawazahmed0/quran-api and writes it as a typed TypeScript module.
// This bundles the data so the "sambung ayat" game runs entirely client-side.
//
// Usage: npm run gen:juz30

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = resolve(__dirname, "..", "src", "data", "juz30.ts");

const PRIMARY = "https://cdn.jsdelivr.net/gh/fawazahmed0/quran-api@1";
const FALLBACK = "https://cdn.statically.io/gh/fawazahmed0/quran-api/1";

// Keep these in sync with src/lib/quran.ts. ara-quranacademy is a clean
// Uthmani Hafs edition that renders without "tofu" in standard Arabic fonts.
const ARABIC = "ara-quranacademy";
const INDONESIAN = "ind-indonesianislam";

const JUZ30 = Array.from({ length: 114 - 78 + 1 }, (_, i) => 78 + i);

async function fetchEdition(edition, chapter) {
  const path = `editions/${edition}/${chapter}.min.json`;
  const urls = [`${PRIMARY}/${path}`, `${FALLBACK}/${path}`];
  let lastError;
  for (const url of urls) {
    try {
      const res = await fetch(url);
      if (!res.ok) {
        lastError = new Error(`${res.status} ${url}`);
        continue;
      }
      const data = await res.json();
      if (!data?.chapter?.length) {
        lastError = new Error(`empty ${url}`);
        continue;
      }
      return data.chapter;
    } catch (err) {
      lastError = err;
    }
  }
  throw lastError ?? new Error("fetch failed");
}

async function fetchChapter(chapter) {
  const [arabic, indonesian] = await Promise.all([
    fetchEdition(ARABIC, chapter),
    fetchEdition(INDONESIAN, chapter),
  ]);
  const indMap = new Map(indonesian.map((v) => [v.verse, v.text]));
  return arabic.map((a) => ({
    verse: a.verse,
    arabic: a.text,
    translation: indMap.get(a.verse) ?? "",
  }));
}

async function main() {
  console.log(`Fetching ${JUZ30.length} chapters from juz 30...`);
  const results = {};
  let done = 0;
  // Limit concurrency to be polite to the CDN.
  const queue = [...JUZ30];
  const workers = Array.from({ length: 6 }, async () => {
    while (queue.length) {
      const chapter = queue.shift();
      const verses = await fetchChapter(chapter);
      results[chapter] = verses;
      done += 1;
      console.log(`  ${done}/${JUZ30.length} surah ${chapter} (${verses.length} ayat)`);
    }
  });
  await Promise.all(workers);

  const ordered = Object.fromEntries(
    JUZ30.map((n) => [n, results[n]]),
  );

  const header = `// AUTO-GENERATED by scripts/fetch-juz30.mjs — do not edit by hand.\n// Source: fawazahmed0/quran-api (editions: ${ARABIC}, ${INDONESIAN})\n\nexport interface Juz30Verse {\n  verse: number;\n  arabic: string;\n  translation: string;\n}\n\nexport const JUZ30_CHAPTERS: Record<number, Juz30Verse[]> = `;

  const body = JSON.stringify(ordered, null, 2);
  const footer = ";\n\nexport const JUZ30_NUMBERS: number[] = [\n  " +
    JUZ30.join(", ") +
    ",\n];\n";

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, header + body + footer);
  console.log(`Wrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
