// AUTO-GENERATED by scripts/fetch-juz30.mjs — do not edit by hand.
// Source: fawazahmed0/quran-api (editions: ara-quranacademy, ind-indonesianislam)

export interface Juz30Verse {
  verse: number;
  arabic: string;
  translation: string;
}

export const JUZ30_CHAPTERS: Record<number, Juz30Verse[]> = {
  "78": [
    {
      "verse": 1,
      "arabic": "۞ عَمَّ یَتَسَاۤءَلُونَ",
      "translation": "Tentang apakah mereka saling bertanya-tanya"
    },
    {
      "verse": 2,
      "arabic": "عَنِ ٱلنَّبَإِ ٱلۡعَظِیمِ",
      "translation": "Tentang berita yang besar (hari berbangkit)"
    },
    {
      "verse": 3,
      "arabic": "ٱلَّذِی هُمۡ فِیهِ مُخۡتَلِفُونَ",
      "translation": "yang dalam hal itu mereka berselisih"
    },
    {
      "verse": 4,
      "arabic": "كَلَّا سَیَعۡلَمُونَ",
      "translation": "(Tidak!892) Kelak mereka akan mengetahui"
    },
    {
      "verse": 5,
      "arabic": "ثُمَّ كَلَّا سَیَعۡلَمُونَ",
      "translation": "sekali lagi tidak! Kelak mereka akan mengetahui"
    },
    {
      "verse": 6,
      "arabic": "أَلَمۡ نَجۡعَلِ ٱلۡأَرۡضَ مِهَـٰدࣰا",
      "translation": "Bukankah Kami telah menjadikan bumi sebagai hamparan"
    },
    {
      "verse": 7,
      "arabic": "وَٱلۡجِبَالَ أَوۡتَادࣰا",
      "translation": "dan gunung-gunung sebagai pasak"
    },
    {
      "verse": 8,
      "arabic": "وَخَلَقۡنَـٰكُمۡ أَزۡوَ ٰجࣰا",
      "translation": "Dan Kami menciptakan kamu berpasang-pasangan"
    },
    {
      "verse": 9,
      "arabic": "وَجَعَلۡنَا نَوۡمَكُمۡ سُبَاتࣰا",
      "translation": "dan Kami menjadikan tidurmu untuk istirahat"
    },
    {
      "verse": 10,
      "arabic": "وَجَعَلۡنَا ٱلَّیۡلَ لِبَاسࣰا",
      "translation": "dan Kami menjadikan malam sebagai pakaian"
    },
    {
      "verse": 11,
      "arabic": "وَجَعَلۡنَا ٱلنَّهَارَ مَعَاشࣰا",
      "translation": "dan Kami menjadikan siang untuk mencari penghidupan"
    },
    {
      "verse": 12,
      "arabic": "وَبَنَیۡنَا فَوۡقَكُمۡ سَبۡعࣰا شِدَادࣰا",
      "translation": "dan Kami membangun di atas kamu tujuh (lapis langit) yang kokoh"
    },
    {
      "verse": 13,
      "arabic": "وَجَعَلۡنَا سِرَاجࣰا وَهَّاجࣰا",
      "translation": "dan Kami menjadikan pelita yang terang-benderang (matahari)"
    },
    {
      "verse": 14,
      "arabic": "وَأَنزَلۡنَا مِنَ ٱلۡمُعۡصِرَ ٰتِ مَاۤءࣰ ثَجَّاجࣰا",
      "translation": "dan Kami turunkan dari awan, air hujan yang tercurah dengan lebatnya"
    },
    {
      "verse": 15,
      "arabic": "لِّنُخۡرِجَ بِهِۦ حَبࣰّا وَنَبَاتࣰا",
      "translation": "untuk Kami tumbuhkan dengan air itu biji-bijian dan tanam-tanaman"
    },
    {
      "verse": 16,
      "arabic": "وَجَنَّـٰتٍ أَلۡفَافًا",
      "translation": "dan kebun-kebun yang rindang"
    },
    {
      "verse": 17,
      "arabic": "إِنَّ یَوۡمَ ٱلۡفَصۡلِ كَانَ مِیقَـٰتࣰا",
      "translation": "Sungguh, hari keputusan adalah suatu waktu yang telah ditetapkan"
    },
    {
      "verse": 18,
      "arabic": "یَوۡمَ یُنفَخُ فِی ٱلصُّورِ فَتَأۡتُونَ أَفۡوَاجࣰا",
      "translation": "(yaitu) pada hari (ketika) sangkakala ditiup, lalu kamu datang berbondong-bondong"
    },
    {
      "verse": 19,
      "arabic": "وَفُتِحَتِ ٱلسَّمَاۤءُ فَكَانَتۡ أَبۡوَ ٰبࣰا",
      "translation": "dan langit pun dibukalah, maka terdapatlah beberapa pintu"
    },
    {
      "verse": 20,
      "arabic": "وَسُیِّرَتِ ٱلۡجِبَالُ فَكَانَتۡ سَرَابًا",
      "translation": "dan gunung-gunungpun dijalankan sehingga menjadi fatamorgana"
    },
    {
      "verse": 21,
      "arabic": "إِنَّ جَهَنَّمَ كَانَتۡ مِرۡصَادࣰا",
      "translation": "Sungguh, (neraka) Jahanam itu (sebagai) tempat mengintai (bagi penjaga yang mengawasi isi neraka)"
    },
    {
      "verse": 22,
      "arabic": "لِّلطَّـٰغِینَ مَءَابࣰا",
      "translation": "menjadi tempat kembali bagi orang-orang yang melampaui batas"
    },
    {
      "verse": 23,
      "arabic": "لَّـٰبِثِینَ فِیهَاۤ أَحۡقَابࣰا",
      "translation": "Mereka tinggal di sana dalam masa yang lama"
    },
    {
      "verse": 24,
      "arabic": "لَّا یَذُوقُونَ فِیهَا بَرۡدࣰا وَلَا شَرَابًا",
      "translation": "mereka tidak merasakan kesejukan di dalamnya dan tidak (pula mendapat) minuman"
    },
    {
      "verse": 25,
      "arabic": "إِلَّا حَمِیمࣰا وَغَسَّاقࣰا",
      "translation": "selain air yang mendidih dan nanah"
    },
    {
      "verse": 26,
      "arabic": "جَزَاۤءࣰ وِفَاقًا",
      "translation": "sebagai pembalasan yang setimpal"
    },
    {
      "verse": 27,
      "arabic": "إِنَّهُمۡ كَانُوا۟ لَا یَرۡجُونَ حِسَابࣰا",
      "translation": "Sesungguhnya dahulu mereka tidak pernah mengharapkan perhitungan"
    },
    {
      "verse": 28,
      "arabic": "وَكَذَّبُوا۟ بِءَایَـٰتِنَا كِذَّابࣰا",
      "translation": "dan mereka benar-benar mendustakan ayat-ayat Kami"
    },
    {
      "verse": 29,
      "arabic": "وَكُلَّ شَیۡءٍ أَحۡصَیۡنَـٰهُ كِتَـٰبࣰا",
      "translation": "Dan segala sesuatu telah Kami catat dalam suatu Kitab (buku catatan amalan manusia)"
    },
    {
      "verse": 30,
      "arabic": "فَذُوقُوا۟ فَلَن نَّزِیدَكُمۡ إِلَّا عَذَابًا",
      "translation": "Maka karena itu rasakanlah! Maka tidak ada yang akan Kami tambahkan kepadamu selain azab"
    },
    {
      "verse": 31,
      "arabic": "إِنَّ لِلۡمُتَّقِینَ مَفَازًا",
      "translation": "Sungguh, orang-orang yang bertakwa mendapat kemenangan"
    },
    {
      "verse": 32,
      "arabic": "حَدَاۤئِقَ وَأَعۡنَـٰبࣰا",
      "translation": "(yaitu) kebun-kebun dan buah anggur"
    },
    {
      "verse": 33,
      "arabic": "وَكَوَاعِبَ أَتۡرَابࣰا",
      "translation": "dan gadis-gadis belia yang sebaya"
    },
    {
      "verse": 34,
      "arabic": "وَكَأۡسࣰا دِهَاقࣰا",
      "translation": "dan gelas-gelas yang penuh (berisi minuman)"
    },
    {
      "verse": 35,
      "arabic": "لَّا یَسۡمَعُونَ فِیهَا لَغۡوࣰا وَلَا كِذَّ ٰبࣰا",
      "translation": "Di sana mereka tidak mendengar percakapan yang sia-sia maupun (perkataan dusta)"
    },
    {
      "verse": 36,
      "arabic": "جَزَاۤءࣰ مِّن رَّبِّكَ عَطَاۤءً حِسَابࣰا",
      "translation": "Sebagai balasan dan pemberian yang cukup banyak dari Tuhanmu"
    },
    {
      "verse": 37,
      "arabic": "رَّبِّ ٱلسَّمَـٰوَ ٰتِ وَٱلۡأَرۡضِ وَمَا بَیۡنَهُمَا ٱلرَّحۡمَـٰنِۖ لَا یَمۡلِكُونَ مِنۡهُ خِطَابࣰا",
      "translation": "Tuhan (yang memelihara) langit dan bumi serta apa yang ada di antara keduanya; Yang Maha Pengasih, mereka tidak mampu berbicara dengan Dia"
    },
    {
      "verse": 38,
      "arabic": "یَوۡمَ یَقُومُ ٱلرُّوحُ وَٱلۡمَلَـٰۤئِكَةُ صَفࣰّاۖ لَّا یَتَكَلَّمُونَ إِلَّا مَنۡ أَذِنَ لَهُ ٱلرَّحۡمَـٰنُ وَقَالَ صَوَابࣰا",
      "translation": "(Pada hari, ketika rūḥ894) dan para malaikat berdiri bersaf-saf, mereka tidak berkata-kata, kecuali siapa yang telah diberi izin kepadanya oleh Tuhan Yang Maha Pengasih dan dia hanya mengatakan yang benar"
    },
    {
      "verse": 39,
      "arabic": "ذَ ٰلِكَ ٱلۡیَوۡمُ ٱلۡحَقُّۖ فَمَن شَاۤءَ ٱتَّخَذَ إِلَىٰ رَبِّهِۦ مَءَابًا",
      "translation": "Itulah hari yang pasti terjadi. Maka barangsiapa menghendaki, niscaya dia menempuh jalan kembali kepada Tuhannya"
    },
    {
      "verse": 40,
      "arabic": "إِنَّاۤ أَنذَرۡنَـٰكُمۡ عَذَابࣰا قَرِیبࣰا یَوۡمَ یَنظُرُ ٱلۡمَرۡءُ مَا قَدَّمَتۡ یَدَاهُ وَیَقُولُ ٱلۡكَافِرُ یَـٰلَیۡتَنِی كُنتُ تُرَ ٰبَۢا",
      "translation": "Sesungguhnya Kami telah memperingatkan kepadamu (orang kafir) azab yang dekat, pada hari manusia melihat apa yang telah diperbuat oleh kedua tangannya; dan orang kafir berkata, \"Alangkah baiknya seandainya dahulu aku jadi tanah"
    }
  ],
  "79": [
    {
      "verse": 1,
      "arabic": "وَٱلنَّـٰزِعَـٰتِ غَرۡقࣰا",
      "translation": "Demi (malaikat) yang mencabut (nyawa) dengan keras"
    },
    {
      "verse": 2,
      "arabic": "وَٱلنَّـٰشِطَـٰتِ نَشۡطࣰا",
      "translation": "Demi (malaikat) yang mencabut (nyawa) dengan lemah lembut"
    },
    {
      "verse": 3,
      "arabic": "وَٱلسَّـٰبِحَـٰتِ سَبۡحࣰا",
      "translation": "Demi (malaikat) yang turun dari langit dengan cepat"
    },
    {
      "verse": 4,
      "arabic": "فَٱلسَّـٰبِقَـٰتِ سَبۡقࣰا",
      "translation": "dan (malaikat) yang mendahului dengan kencang"
    },
    {
      "verse": 5,
      "arabic": "فَٱلۡمُدَبِّرَ ٰتِ أَمۡرࣰا",
      "translation": "dan (malaikat) yang mengatur urusan (dunia)"
    },
    {
      "verse": 6,
      "arabic": "یَوۡمَ تَرۡجُفُ ٱلرَّاجِفَةُ",
      "translation": "(Sungguh, kamu akan dibangkitkan) pada hari ketika tiupan pertama mengguncangkan alam"
    },
    {
      "verse": 7,
      "arabic": "تَتۡبَعُهَا ٱلرَّادِفَةُ",
      "translation": "(tiupan pertama) itu diiringi oleh tiupan kedua"
    },
    {
      "verse": 8,
      "arabic": "قُلُوبࣱ یَوۡمَئِذࣲ وَاجِفَةٌ",
      "translation": "Hati manusia pada waktu itu merasa sangat takut"
    },
    {
      "verse": 9,
      "arabic": "أَبۡصَـٰرُهَا خَـٰشِعَةࣱ",
      "translation": "pandangannya tunduk"
    },
    {
      "verse": 10,
      "arabic": "یَقُولُونَ أَءِنَّا لَمَرۡدُودُونَ فِی ٱلۡحَافِرَةِ",
      "translation": "(orang-orang kafir) berkata, \"Apakah kita benar-benar akan dikembalikan kepada kehidupan yang semula"
    },
    {
      "verse": 11,
      "arabic": "أَءِذَا كُنَّا عِظَـٰمࣰا نَّخِرَةࣰ",
      "translation": "Apakah (akan dibangkitkan juga) apabila kita telah menjadi tulang belulang yang hancur"
    },
    {
      "verse": 12,
      "arabic": "قَالُوا۟ تِلۡكَ إِذࣰا كَرَّةٌ خَاسِرَةࣱ",
      "translation": "Mereka berkata, \"Kalau demikian, itu adalah suatu pengembalian yang merugikan"
    },
    {
      "verse": 13,
      "arabic": "فَإِنَّمَا هِیَ زَجۡرَةࣱ وَ ٰحِدَةࣱ",
      "translation": "Maka pengembalian itu hanyalah dengan sekali tiupan saja"
    },
    {
      "verse": 14,
      "arabic": "فَإِذَا هُم بِٱلسَّاهِرَةِ",
      "translation": "Maka seketika itu mereka hidup kembali di bumi (yang baru)"
    },
    {
      "verse": 15,
      "arabic": "هَلۡ أَتَىٰكَ حَدِیثُ مُوسَىٰۤ",
      "translation": "Sudahkah sampai kepadamu (Muhammad) kisah Musa"
    },
    {
      "verse": 16,
      "arabic": "إِذۡ نَادَىٰهُ رَبُّهُۥ بِٱلۡوَادِ ٱلۡمُقَدَّسِ طُوًى",
      "translation": "Ketika Tuhan memanggilnya (Musa) di lembah suci yaitu Lembah Tuwa"
    },
    {
      "verse": 17,
      "arabic": "ٱذۡهَبۡ إِلَىٰ فِرۡعَوۡنَ إِنَّهُۥ طَغَىٰ",
      "translation": "pergilah engkau kepada Fir'aun! Sesungguhnya dia telah melampaui batas"
    },
    {
      "verse": 18,
      "arabic": "فَقُلۡ هَل لَّكَ إِلَىٰۤ أَن تَزَكَّىٰ",
      "translation": "Maka katakanlah (kepada Fir'aun), \"Adakah keinginanmu untuk membersihkan diri (dari kesesatan)"
    },
    {
      "verse": 19,
      "arabic": "وَأَهۡدِیَكَ إِلَىٰ رَبِّكَ فَتَخۡشَىٰ",
      "translation": "dan engkau akan kubimbing ke jalan Tuhanmu agar engkau takut kepada-Nya"
    },
    {
      "verse": 20,
      "arabic": "فَأَرَىٰهُ ٱلۡءَایَةَ ٱلۡكُبۡرَىٰ",
      "translation": "Lalu (Musa) memperlihatkan kepadanya mukjizat yang besar"
    },
    {
      "verse": 21,
      "arabic": "فَكَذَّبَ وَعَصَىٰ",
      "translation": "Tetapi dia (Fir'aun) mendustakan dan mendurhakai"
    },
    {
      "verse": 22,
      "arabic": "ثُمَّ أَدۡبَرَ یَسۡعَىٰ",
      "translation": "Kemudian dia berpaling seraya berusaha menantang (Musa)"
    },
    {
      "verse": 23,
      "arabic": "فَحَشَرَ فَنَادَىٰ",
      "translation": "Kemudian dia mengumpulkan (pembesar-pembesarnya) lalu berseru (memanggil kaumnya)"
    },
    {
      "verse": 24,
      "arabic": "فَقَالَ أَنَا۠ رَبُّكُمُ ٱلۡأَعۡلَىٰ",
      "translation": "(Seraya) berkata, \"Akulah tuhanmu yang paling tinggi"
    },
    {
      "verse": 25,
      "arabic": "فَأَخَذَهُ ٱللَّهُ نَكَالَ ٱلۡءَاخِرَةِ وَٱلۡأُولَىٰۤ",
      "translation": "Maka Allah menghukumnya dengan azab di akhirat dan siksaan di dunia"
    },
    {
      "verse": 26,
      "arabic": "إِنَّ فِی ذَ ٰلِكَ لَعِبۡرَةࣰ لِّمَن یَخۡشَىٰۤ",
      "translation": "Sungguh, pada yang demikian itu terdapat pelajaran bagi orang yang takut (kepada Allah)"
    },
    {
      "verse": 27,
      "arabic": "ءَأَنتُمۡ أَشَدُّ خَلۡقًا أَمِ ٱلسَّمَاۤءُۚ بَنَىٰهَا",
      "translation": "Apakah penciptaan kamu yang lebih hebat ataukah langit yang telah dibangun-Nya"
    },
    {
      "verse": 28,
      "arabic": "رَفَعَ سَمۡكَهَا فَسَوَّىٰهَا",
      "translation": "Dia telah meninggikan bangunannya lalu menyempurnakannya"
    },
    {
      "verse": 29,
      "arabic": "وَأَغۡطَشَ لَیۡلَهَا وَأَخۡرَجَ ضُحَىٰهَا",
      "translation": "dan Dia menjadikan malamnya (gelap gulita), dan menjadikan siangnya (terang benderang)"
    },
    {
      "verse": 30,
      "arabic": "وَٱلۡأَرۡضَ بَعۡدَ ذَ ٰلِكَ دَحَىٰهَاۤ",
      "translation": "Dan setelah itu bumi Dia hamparkan"
    },
    {
      "verse": 31,
      "arabic": "أَخۡرَجَ مِنۡهَا مَاۤءَهَا وَمَرۡعَىٰهَا",
      "translation": "Darinya Dia pancarkan mata air, dan (ditumbuhkan) tumbuh-tumbuhannya"
    },
    {
      "verse": 32,
      "arabic": "وَٱلۡجِبَالَ أَرۡسَىٰهَا",
      "translation": "Dan gunung-gunung Dia pancangkan dengan kokoh"
    },
    {
      "verse": 33,
      "arabic": "مَتَـٰعࣰا لَّكُمۡ وَلِأَنۡعَـٰمِكُمۡ",
      "translation": "(Semua itu) untuk kesenanganmu dan untuk hewan-hewan ternakmu"
    },
    {
      "verse": 34,
      "arabic": "فَإِذَا جَاۤءَتِ ٱلطَّاۤمَّةُ ٱلۡكُبۡرَىٰ",
      "translation": "Maka apabila malapetaka besar (hari Kiamat) telah datang"
    },
    {
      "verse": 35,
      "arabic": "یَوۡمَ یَتَذَكَّرُ ٱلۡإِنسَـٰنُ مَا سَعَىٰ",
      "translation": "yaitu pada hari (ketika) manusia teringat akan apa yang telah dikerjakannya"
    },
    {
      "verse": 36,
      "arabic": "وَبُرِّزَتِ ٱلۡجَحِیمُ لِمَن یَرَىٰ",
      "translation": "dan neraka diperlihatkan dengan jelas kepada setiap orang yang melihat"
    },
    {
      "verse": 37,
      "arabic": "فَأَمَّا مَن طَغَىٰ",
      "translation": "Maka adapun orang yang melampaui batas"
    },
    {
      "verse": 38,
      "arabic": "وَءَاثَرَ ٱلۡحَیَوٰةَ ٱلدُّنۡیَا",
      "translation": "dan lebih mengutamakan kehidupan dunia"
    },
    {
      "verse": 39,
      "arabic": "فَإِنَّ ٱلۡجَحِیمَ هِیَ ٱلۡمَأۡوَىٰ",
      "translation": "maka sungguh, nerakalah tempat tinggalnya"
    },
    {
      "verse": 40,
      "arabic": "وَأَمَّا مَنۡ خَافَ مَقَامَ رَبِّهِۦ وَنَهَى ٱلنَّفۡسَ عَنِ ٱلۡهَوَىٰ",
      "translation": "Dan adapun orang-orang yang takut kepada kebesaran Tuhannya dan menahan diri dari (keinginan) hawa nafsunya"
    },
    {
      "verse": 41,
      "arabic": "فَإِنَّ ٱلۡجَنَّةَ هِیَ ٱلۡمَأۡوَىٰ",
      "translation": "maka sungguh, surgalah tempat tinggal-(nya)"
    },
    {
      "verse": 42,
      "arabic": "یَسۡءَلُونَكَ عَنِ ٱلسَّاعَةِ أَیَّانَ مُرۡسَىٰهَا",
      "translation": "Mereka (orang-orang kafir) bertanya kepadamu (Muhammad) tentang hari Kiamat, \"Kapankah terjadinya"
    },
    {
      "verse": 43,
      "arabic": "فِیمَ أَنتَ مِن ذِكۡرَىٰهَاۤ",
      "translation": "Untuk apa engkau perlu menyebutkannya (waktunya)"
    },
    {
      "verse": 44,
      "arabic": "إِلَىٰ رَبِّكَ مُنتَهَىٰهَاۤ",
      "translation": "Kepada Tuhanmulah (dikembalikan) kesudahannya (ketentuan waktunya)"
    },
    {
      "verse": 45,
      "arabic": "إِنَّمَاۤ أَنتَ مُنذِرُ مَن یَخۡشَىٰهَا",
      "translation": "Engkau (Muhammad) hanyalah pemberi peringatan bagi siapa yang takut kepadanya (hari Kiamat)"
    },
    {
      "verse": 46,
      "arabic": "كَأَنَّهُمۡ یَوۡمَ یَرَوۡنَهَا لَمۡ یَلۡبَثُوۤا۟ إِلَّا عَشِیَّةً أَوۡ ضُحَىٰهَا",
      "translation": "Pada hari ketika mereka melihat hari Kiamat itu (karena suasananya hebat), mereka merasa seakan-akan hanya (sebentar saja) tinggal (di dunia) pada waktu sore atau pagi hari"
    }
  ],
  "80": [
    {
      "verse": 1,
      "arabic": "۞ عَبَسَ وَتَوَلَّىٰۤ",
      "translation": "Dia (Muhammad) berwajah masam dan berpaling"
    },
    {
      "verse": 2,
      "arabic": "أَن جَاۤءَهُ ٱلۡأَعۡمَىٰ",
      "translation": "karena seorang buta telah datang kepadanya (Abdullah bin Ummi Maktum)"
    },
    {
      "verse": 3,
      "arabic": "وَمَا یُدۡرِیكَ لَعَلَّهُۥ یَزَّكَّىٰۤ",
      "translation": "Dan tahukah engkau (Muhammad) barangkali dia ingin menyucikan dirinya (dari dosa)"
    },
    {
      "verse": 4,
      "arabic": "أَوۡ یَذَّكَّرُ فَتَنفَعَهُ ٱلذِّكۡرَىٰۤ",
      "translation": "atau dia (ingin) mendapatkan pengajaran, yang memberi manfaat kepadanya"
    },
    {
      "verse": 5,
      "arabic": "أَمَّا مَنِ ٱسۡتَغۡنَىٰ",
      "translation": "Adapun orang yang merasa dirinya serba cukup (pembesar-pembesar Quraisy)"
    },
    {
      "verse": 6,
      "arabic": "فَأَنتَ لَهُۥ تَصَدَّىٰ",
      "translation": "maka engkau (Muhammad) memberi perhatian kepadanya"
    },
    {
      "verse": 7,
      "arabic": "وَمَا عَلَیۡكَ أَلَّا یَزَّكَّىٰ",
      "translation": "padahal tidak ada (cela) atasmu kalau dia tidak menyucikan diri (beriman)"
    },
    {
      "verse": 8,
      "arabic": "وَأَمَّا مَن جَاۤءَكَ یَسۡعَىٰ",
      "translation": "Dan adapun orang yang datang kepadamu dengan bersegera (untuk mendapatkan pengajaran)"
    },
    {
      "verse": 9,
      "arabic": "وَهُوَ یَخۡشَىٰ",
      "translation": "sedang dia takut (kepada Allah)"
    },
    {
      "verse": 10,
      "arabic": "فَأَنتَ عَنۡهُ تَلَهَّىٰ",
      "translation": "engkau (Muhammad) malah mengabaikannya"
    },
    {
      "verse": 11,
      "arabic": "كَلَّاۤ إِنَّهَا تَذۡكِرَةࣱ",
      "translation": "Sekali-kali jangan (begitu)! Sungguh, (ajaran-ajaran Allah) itu suatu peringatan"
    },
    {
      "verse": 12,
      "arabic": "فَمَن شَاۤءَ ذَكَرَهُۥ",
      "translation": "maka barangsiapa menghendaki, tentulah dia akan memperhatikannya"
    },
    {
      "verse": 13,
      "arabic": "فِی صُحُفࣲ مُّكَرَّمَةࣲ",
      "translation": "di dalam kitab-kitab yang dimuliakan (di sisi Allah)"
    },
    {
      "verse": 14,
      "arabic": "مَّرۡفُوعَةࣲ مُّطَهَّرَةِۭ",
      "translation": "yang ditinggikan (dan) disucikan"
    },
    {
      "verse": 15,
      "arabic": "بِأَیۡدِی سَفَرَةࣲ",
      "translation": "di tangan para utusan (malaikat)"
    },
    {
      "verse": 16,
      "arabic": "كِرَامِۭ بَرَرَةࣲ",
      "translation": "yang mulia lagi berbakti"
    },
    {
      "verse": 17,
      "arabic": "قُتِلَ ٱلۡإِنسَـٰنُ مَاۤ أَكۡفَرَهُۥ",
      "translation": "Celakalah manusia! Alangkah kufurnya dia"
    },
    {
      "verse": 18,
      "arabic": "مِنۡ أَیِّ شَیۡءٍ خَلَقَهُۥ",
      "translation": "Dari apakah Dia (Allah) menciptakannya"
    },
    {
      "verse": 19,
      "arabic": "مِن نُّطۡفَةٍ خَلَقَهُۥ فَقَدَّرَهُۥ",
      "translation": "Dari setetes mani, Dia menciptakannya lalu menentukannya"
    },
    {
      "verse": 20,
      "arabic": "ثُمَّ ٱلسَّبِیلَ یَسَّرَهُۥ",
      "translation": "Kemudian jalannya Dia mudahkan"
    },
    {
      "verse": 21,
      "arabic": "ثُمَّ أَمَاتَهُۥ فَأَقۡبَرَهُۥ",
      "translation": "kemudian Dia mematikannya lalu menguburkannya"
    },
    {
      "verse": 22,
      "arabic": "ثُمَّ إِذَا شَاۤءَ أَنشَرَهُۥ",
      "translation": "kemudian jika Dia menghendaki, Dia membangkitkannya kembali"
    },
    {
      "verse": 23,
      "arabic": "كَلَّا لَمَّا یَقۡضِ مَاۤ أَمَرَهُۥ",
      "translation": "Sekali-kali jangan (begitu)! Dia (manusia) itu belum melaksanakan apa yang Dia (Allah) perintahkan kepadanya"
    },
    {
      "verse": 24,
      "arabic": "فَلۡیَنظُرِ ٱلۡإِنسَـٰنُ إِلَىٰ طَعَامِهِۦۤ",
      "translation": "Maka hendaklah manusia itu memperhatikan makanannya"
    },
    {
      "verse": 25,
      "arabic": "أَنَّا صَبَبۡنَا ٱلۡمَاۤءَ صَبࣰّا",
      "translation": "Kamilah yang telah mencurahkan air melimpah (dari langit)"
    },
    {
      "verse": 26,
      "arabic": "ثُمَّ شَقَقۡنَا ٱلۡأَرۡضَ شَقࣰّا",
      "translation": "kemudian Kami belah bumi dengan sebaik-baiknya"
    },
    {
      "verse": 27,
      "arabic": "فَأَنۢبَتۡنَا فِیهَا حَبࣰّا",
      "translation": "lalu di sana Kami tumbuhkan biji-bijian"
    },
    {
      "verse": 28,
      "arabic": "وَعِنَبࣰا وَقَضۡبࣰا",
      "translation": "dan anggur dan sayur-sayuran"
    },
    {
      "verse": 29,
      "arabic": "وَزَیۡتُونࣰا وَنَخۡلࣰا",
      "translation": "dan zaitun dan pohon kurma"
    },
    {
      "verse": 30,
      "arabic": "وَحَدَاۤئِقَ غُلۡبࣰا",
      "translation": "dan kebun-kebun (yang) rindang"
    },
    {
      "verse": 31,
      "arabic": "وَفَـٰكِهَةࣰ وَأَبࣰّا",
      "translation": "dan buah-buahan serta rerumputan"
    },
    {
      "verse": 32,
      "arabic": "مَّتَـٰعࣰا لَّكُمۡ وَلِأَنۡعَـٰمِكُمۡ",
      "translation": "(Semua itu) untuk kesenanganmu dan untuk hewan-hewan ternakmu"
    },
    {
      "verse": 33,
      "arabic": "فَإِذَا جَاۤءَتِ ٱلصَّاۤخَّةُ",
      "translation": "Maka apabila datang suara yang memekakkan (tiupan sangkakala yang kedua)"
    },
    {
      "verse": 34,
      "arabic": "یَوۡمَ یَفِرُّ ٱلۡمَرۡءُ مِنۡ أَخِیهِ",
      "translation": "pada hari itu manusia lari dari saudaranya"
    },
    {
      "verse": 35,
      "arabic": "وَأُمِّهِۦ وَأَبِیهِ",
      "translation": "dan dari ibu dan bapaknya"
    },
    {
      "verse": 36,
      "arabic": "وَصَـٰحِبَتِهِۦ وَبَنِیهِ",
      "translation": "dan dari istri dan anak-anaknya"
    },
    {
      "verse": 37,
      "arabic": "لِكُلِّ ٱمۡرِئࣲ مِّنۡهُمۡ یَوۡمَئِذࣲ شَأۡنࣱ یُغۡنِیهِ",
      "translation": "Setiap orang dari mereka pada hari itu mempunyai urusan yang menyibukkannya"
    },
    {
      "verse": 38,
      "arabic": "وُجُوهࣱ یَوۡمَئِذࣲ مُّسۡفِرَةࣱ",
      "translation": "Pada hari itu ada wajah-wajah yang berseri-seri"
    },
    {
      "verse": 39,
      "arabic": "ضَاحِكَةࣱ مُّسۡتَبۡشِرَةࣱ",
      "translation": "tertawa dan gembira ria"
    },
    {
      "verse": 40,
      "arabic": "وَوُجُوهࣱ یَوۡمَئِذٍ عَلَیۡهَا غَبَرَةࣱ",
      "translation": "dan pada hari itu ada (pula) wajah-wajah yang tertutup debu (suram)"
    },
    {
      "verse": 41,
      "arabic": "تَرۡهَقُهَا قَتَرَةٌ",
      "translation": "tertutup oleh kegelapan (ditimpa kehinaan dan kesusahan)"
    },
    {
      "verse": 42,
      "arabic": "أُو۟لَـٰۤئِكَ هُمُ ٱلۡكَفَرَةُ ٱلۡفَجَرَةُ",
      "translation": "Mereka itulah orang-orang kafir yang durhaka"
    }
  ],
  "81": [
    {
      "verse": 1,
      "arabic": "إِذَا ٱلشَّمۡسُ كُوِّرَتۡ",
      "translation": "Apabila matahari digulung"
    },
    {
      "verse": 2,
      "arabic": "وَإِذَا ٱلنُّجُومُ ٱنكَدَرَتۡ",
      "translation": "dan apabila bintang-bintang berjatuhan"
    },
    {
      "verse": 3,
      "arabic": "وَإِذَا ٱلۡجِبَالُ سُیِّرَتۡ",
      "translation": "dan apabila gunung-gunung dihancurkan"
    },
    {
      "verse": 4,
      "arabic": "وَإِذَا ٱلۡعِشَارُ عُطِّلَتۡ",
      "translation": "dan apabila unta-unta yang bunting ditinggalkan (tidak terurus)"
    },
    {
      "verse": 5,
      "arabic": "وَإِذَا ٱلۡوُحُوشُ حُشِرَتۡ",
      "translation": "dan apabila binatang-binatang liar dikumpulkan"
    },
    {
      "verse": 6,
      "arabic": "وَإِذَا ٱلۡبِحَارُ سُجِّرَتۡ",
      "translation": "dan apabila lautan dipanaskan"
    },
    {
      "verse": 7,
      "arabic": "وَإِذَا ٱلنُّفُوسُ زُوِّجَتۡ",
      "translation": "dan apabila roh-roh dipertemukan (dengan tubuh)"
    },
    {
      "verse": 8,
      "arabic": "وَإِذَا ٱلۡمَوۡءُۥدَةُ سُئِلَتۡ",
      "translation": "dan apabila bayi-bayi perempuan yang dikubur hidup-hidup ditanya"
    },
    {
      "verse": 9,
      "arabic": "بِأَیِّ ذَنۢبࣲ قُتِلَتۡ",
      "translation": "karena dosa apa dia dibunuh"
    },
    {
      "verse": 10,
      "arabic": "وَإِذَا ٱلصُّحُفُ نُشِرَتۡ",
      "translation": "Dan apabila lembaran-lembaran (catatan amal) telah dibuka lebar-lebar"
    },
    {
      "verse": 11,
      "arabic": "وَإِذَا ٱلسَّمَاۤءُ كُشِطَتۡ",
      "translation": "dan apabila langit dilenyapkan"
    },
    {
      "verse": 12,
      "arabic": "وَإِذَا ٱلۡجَحِیمُ سُعِّرَتۡ",
      "translation": "dan apabila neraka Jahim dinyalakan"
    },
    {
      "verse": 13,
      "arabic": "وَإِذَا ٱلۡجَنَّةُ أُزۡلِفَتۡ",
      "translation": "dan apabila surga didekatkan"
    },
    {
      "verse": 14,
      "arabic": "عَلِمَتۡ نَفۡسࣱ مَّاۤ أَحۡضَرَتۡ",
      "translation": "setiap jiwa akan mengetahui apa yang telah dikerjakannya"
    },
    {
      "verse": 15,
      "arabic": "فَلَاۤ أُقۡسِمُ بِٱلۡخُنَّسِ",
      "translation": "Aku bersumpah demi bintang-bintang"
    },
    {
      "verse": 16,
      "arabic": "ٱلۡجَوَارِ ٱلۡكُنَّسِ",
      "translation": "yang beredar dan terbenam"
    },
    {
      "verse": 17,
      "arabic": "وَٱلَّیۡلِ إِذَا عَسۡعَسَ",
      "translation": "demi malam apabila telah larut"
    },
    {
      "verse": 18,
      "arabic": "وَٱلصُّبۡحِ إِذَا تَنَفَّسَ",
      "translation": "dan demi subuh apabila telah menyinsing"
    },
    {
      "verse": 19,
      "arabic": "إِنَّهُۥ لَقَوۡلُ رَسُولࣲ كَرِیمࣲ",
      "translation": "sesungguhnya (Alquran) itu benar-benar firman (Allah yang dibawa oleh) utusan yang mulia (Jibril)"
    },
    {
      "verse": 20,
      "arabic": "ذِی قُوَّةٍ عِندَ ذِی ٱلۡعَرۡشِ مَكِینࣲ",
      "translation": "yang memiliki kekuatan, memiliki kedudukan tinggi di sisi (Allah) yang memiliki Arasy"
    },
    {
      "verse": 21,
      "arabic": "مُّطَاعࣲ ثَمَّ أَمِینࣲ",
      "translation": "yang di sana (di alam malaikat) ditaati dan dipercaya"
    },
    {
      "verse": 22,
      "arabic": "وَمَا صَاحِبُكُم بِمَجۡنُونࣲ",
      "translation": "Dan temanmu (Muhammad) itu bukanlah orang gila"
    },
    {
      "verse": 23,
      "arabic": "وَلَقَدۡ رَءَاهُ بِٱلۡأُفُقِ ٱلۡمُبِینِ",
      "translation": "Dan sungguh, dia (Muhammad) telah melihatnya (Jibril) di ufuk yang terang"
    },
    {
      "verse": 24,
      "arabic": "وَمَا هُوَ عَلَى ٱلۡغَیۡبِ بِضَنِینࣲ",
      "translation": "Dan Dia (Muhammad) bukanlah seorang yang kikir (enggan) untuk menerangkan yang gaib"
    },
    {
      "verse": 25,
      "arabic": "وَمَا هُوَ بِقَوۡلِ شَیۡطَـٰنࣲ رَّجِیمࣲ",
      "translation": "Dan (Alquran) itu bukanlah perkataan setan yang terkutuk"
    },
    {
      "verse": 26,
      "arabic": "فَأَیۡنَ تَذۡهَبُونَ",
      "translation": "maka ke manakah kamu akan pergi"
    },
    {
      "verse": 27,
      "arabic": "إِنۡ هُوَ إِلَّا ذِكۡرࣱ لِّلۡعَـٰلَمِینَ",
      "translation": "(Alquran) itu tidak lain adalah peringatan bagi seluruh alam"
    },
    {
      "verse": 28,
      "arabic": "لِمَن شَاۤءَ مِنكُمۡ أَن یَسۡتَقِیمَ",
      "translation": "(yaitu) bagi siapa di antara kamu yang menghendaki menempuh jalan yang lurus"
    },
    {
      "verse": 29,
      "arabic": "وَمَا تَشَاۤءُونَ إِلَّاۤ أَن یَشَاۤءَ ٱللَّهُ رَبُّ ٱلۡعَـٰلَمِینَ",
      "translation": "Dan kamu tidak dapat menghendaki (menempuh jalan itu) kecuali apabila dikehendaki Allah, Tuhan seluruh alam"
    }
  ],
  "82": [
    {
      "verse": 1,
      "arabic": "۞ إِذَا ٱلسَّمَاۤءُ ٱنفَطَرَتۡ",
      "translation": "Apabila langit terbelah"
    },
    {
      "verse": 2,
      "arabic": "وَإِذَا ٱلۡكَوَاكِبُ ٱنتَثَرَتۡ",
      "translation": "dan apabila bintang-bintang jatuh berserakan"
    },
    {
      "verse": 3,
      "arabic": "وَإِذَا ٱلۡبِحَارُ فُجِّرَتۡ",
      "translation": "dan apabila lautan dijadikan meluap"
    },
    {
      "verse": 4,
      "arabic": "وَإِذَا ٱلۡقُبُورُ بُعۡثِرَتۡ",
      "translation": "dan apabila kuburan-kuburan dibongkar"
    },
    {
      "verse": 5,
      "arabic": "عَلِمَتۡ نَفۡسࣱ مَّا قَدَّمَتۡ وَأَخَّرَتۡ",
      "translation": "(maka) setiap jiwa akan mengetahui apa yang telah dikerjakan dan yang dilalaikan(nya)"
    },
    {
      "verse": 6,
      "arabic": "یَـٰۤأَیُّهَا ٱلۡإِنسَـٰنُ مَا غَرَّكَ بِرَبِّكَ ٱلۡكَرِیمِ",
      "translation": "Wahai manusia! Apakah yang telah memperdayakan kamu (berbuat durhaka) terhadap Tuhanmu Yang Maha Pengasih"
    },
    {
      "verse": 7,
      "arabic": "ٱلَّذِی خَلَقَكَ فَسَوَّىٰكَ فَعَدَلَكَ",
      "translation": "Yang telah menciptakanmu lalu menyempurnakan kejadianmu dan menjadikan (susunan tubuh)mu seimbang"
    },
    {
      "verse": 8,
      "arabic": "فِیۤ أَیِّ صُورَةࣲ مَّا شَاۤءَ رَكَّبَكَ",
      "translation": "dalam bentuk apa saja yang dikehendaki, Dia menyusun tubuhmu"
    },
    {
      "verse": 9,
      "arabic": "كَلَّا بَلۡ تُكَذِّبُونَ بِٱلدِّینِ",
      "translation": "Sekali-kali jangan begitu! Bahkan kamu mendustakan hari pembalasan"
    },
    {
      "verse": 10,
      "arabic": "وَإِنَّ عَلَیۡكُمۡ لَحَـٰفِظِینَ",
      "translation": "Dan sesungguhnya bagi kamu ada (malaikat-malaikat) yang mengawasi (pekerjaanmu)"
    },
    {
      "verse": 11,
      "arabic": "كِرَامࣰا كَـٰتِبِینَ",
      "translation": "yang mulia (di sisi Allah) dan yang mencatat (perbuatanmu)"
    },
    {
      "verse": 12,
      "arabic": "یَعۡلَمُونَ مَا تَفۡعَلُونَ",
      "translation": "mereka mengetahui apa yang kamu kerjakan"
    },
    {
      "verse": 13,
      "arabic": "إِنَّ ٱلۡأَبۡرَارَ لَفِی نَعِیمࣲ",
      "translation": "Sesungguhnya orang-orang yang berbakti benar-benar berada dalam (surga yang penuh) kenikmatan"
    },
    {
      "verse": 14,
      "arabic": "وَإِنَّ ٱلۡفُجَّارَ لَفِی جَحِیمࣲ",
      "translation": "dan sesungguhnya orang-orang yang durhaka benar-benar berada dalam neraka"
    },
    {
      "verse": 15,
      "arabic": "یَصۡلَوۡنَهَا یَوۡمَ ٱلدِّینِ",
      "translation": "Mereka masuk ke dalamnya pada hari pembalasan"
    },
    {
      "verse": 16,
      "arabic": "وَمَا هُمۡ عَنۡهَا بِغَاۤئِبِینَ",
      "translation": "Dan mereka tidak mungkin keluar dari neraka itu"
    },
    {
      "verse": 17,
      "arabic": "وَمَاۤ أَدۡرَىٰكَ مَا یَوۡمُ ٱلدِّینِ",
      "translation": "Dan tahukah kamu apakah hari pembalasan itu"
    },
    {
      "verse": 18,
      "arabic": "ثُمَّ مَاۤ أَدۡرَىٰكَ مَا یَوۡمُ ٱلدِّینِ",
      "translation": "Sekali lagi, tahukah kamu apakah hari pembalasan itu"
    },
    {
      "verse": 19,
      "arabic": "یَوۡمَ لَا تَمۡلِكُ نَفۡسࣱ لِّنَفۡسࣲ شَیۡءࣰاۖ وَٱلۡأَمۡرُ یَوۡمَئِذࣲ لِّلَّهِ",
      "translation": "(Yaitu) pada hari (ketika) seseorang sama sekali tidak berdaya (menolong) orang lain. Dan segala urusan pada hari itu dalam kekuasaan Allah"
    }
  ],
  "83": [
    {
      "verse": 1,
      "arabic": "وَیۡلࣱ لِّلۡمُطَفِّفِینَ",
      "translation": "Celakalah bagi orang-orang yang curang (dalam menakar dan menimbang)"
    },
    {
      "verse": 2,
      "arabic": "ٱلَّذِینَ إِذَا ٱكۡتَالُوا۟ عَلَى ٱلنَّاسِ یَسۡتَوۡفُونَ",
      "translation": "(yaitu) orang-orang yang apabila menerima takaran dari orang lain mereka minta dicukupkan"
    },
    {
      "verse": 3,
      "arabic": "وَإِذَا كَالُوهُمۡ أَو وَّزَنُوهُمۡ یُخۡسِرُونَ",
      "translation": "dan apabila mereka menakar atau menimbang (untuk orang lain), mereka mengurangi"
    },
    {
      "verse": 4,
      "arabic": "أَلَا یَظُنُّ أُو۟لَـٰۤئِكَ أَنَّهُم مَّبۡعُوثُونَ",
      "translation": "Tidakkah mereka itu mengira, bahwa sesungguhnya mereka akan dibangkitkan"
    },
    {
      "verse": 5,
      "arabic": "لِیَوۡمٍ عَظِیمࣲ",
      "translation": "pada suatu hari yang besar"
    },
    {
      "verse": 6,
      "arabic": "یَوۡمَ یَقُومُ ٱلنَّاسُ لِرَبِّ ٱلۡعَـٰلَمِینَ",
      "translation": "(yaitu) pada hari (ketika) semua orang bangkit menghadap Tuhan seluruh alam"
    },
    {
      "verse": 7,
      "arabic": "كَلَّاۤ إِنَّ كِتَـٰبَ ٱلۡفُجَّارِ لَفِی سِجِّینࣲ",
      "translation": "Sekali-kali jangan begitu! Sesungguhnya catatan orang yang durhaka benar-benar tersimpan dalam Sijjīn"
    },
    {
      "verse": 8,
      "arabic": "وَمَاۤ أَدۡرَىٰكَ مَا سِجِّینࣱ",
      "translation": "Dan tahukah engkau apakah Sijjīn itu"
    },
    {
      "verse": 9,
      "arabic": "كِتَـٰبࣱ مَّرۡقُومࣱ",
      "translation": "(Yaitu) Kitab yang berisi catatan (amal)"
    },
    {
      "verse": 10,
      "arabic": "وَیۡلࣱ یَوۡمَئِذࣲ لِّلۡمُكَذِّبِینَ",
      "translation": "Celakalah pada hari itu, bagi orang-orang yang mendustakan"
    },
    {
      "verse": 11,
      "arabic": "ٱلَّذِینَ یُكَذِّبُونَ بِیَوۡمِ ٱلدِّینِ",
      "translation": "(yaitu) orang-orang yang mendustakannya (hari pembalasan)"
    },
    {
      "verse": 12,
      "arabic": "وَمَا یُكَذِّبُ بِهِۦۤ إِلَّا كُلُّ مُعۡتَدٍ أَثِیمٍ",
      "translation": "Dan tidak ada yang mendustakannya (hari pembalasan) kecuali setiap orang yang melampaui batas dan berdosa"
    },
    {
      "verse": 13,
      "arabic": "إِذَا تُتۡلَىٰ عَلَیۡهِ ءَایَـٰتُنَا قَالَ أَسَـٰطِیرُ ٱلۡأَوَّلِینَ",
      "translation": "yang apabila dibacakan kepadanya ayat-ayat Kami, dia berkata, \"Itu adalah dongeng orang-orang dahulu"
    },
    {
      "verse": 14,
      "arabic": "كَلَّاۖ بَلۡۜ رَانَ عَلَىٰ قُلُوبِهِم مَّا كَانُوا۟ یَكۡسِبُونَ",
      "translation": "Sekali-kali tidak! Bahkan apa yang mereka kerjakan itu telah menutupi hati mereka"
    },
    {
      "verse": 15,
      "arabic": "كَلَّاۤ إِنَّهُمۡ عَن رَّبِّهِمۡ یَوۡمَئِذࣲ لَّمَحۡجُوبُونَ",
      "translation": "(Sekali-kali tidak!901) Sesungguhnya mereka pada hari itu benar-benar terhalang dari (melihat) Tuhannya"
    },
    {
      "verse": 16,
      "arabic": "ثُمَّ إِنَّهُمۡ لَصَالُوا۟ ٱلۡجَحِیمِ",
      "translation": "Kemudian, sesungguhnya mereka benar-benar masuk neraka"
    },
    {
      "verse": 17,
      "arabic": "ثُمَّ یُقَالُ هَـٰذَا ٱلَّذِی كُنتُم بِهِۦ تُكَذِّبُونَ",
      "translation": "Kemudian, dikatakan (kepada mereka), \"Inilah (azab) yang dahulu kamu dustakan"
    },
    {
      "verse": 18,
      "arabic": "كَلَّاۤ إِنَّ كِتَـٰبَ ٱلۡأَبۡرَارِ لَفِی عِلِّیِّینَ",
      "translation": "Sekali-kali tidak! Sesungguhnya catatan orang-orang yang berbakti benar-benar tersimpan dalam 'Illiyyīn"
    },
    {
      "verse": 19,
      "arabic": "وَمَاۤ أَدۡرَىٰكَ مَا عِلِّیُّونَ",
      "translation": "Dan tahukah engkau apakah 'Illiyyīn itu"
    },
    {
      "verse": 20,
      "arabic": "كِتَـٰبࣱ مَّرۡقُومࣱ",
      "translation": "(Yaitu) Kitab yang berisi catatan (amal)"
    },
    {
      "verse": 21,
      "arabic": "یَشۡهَدُهُ ٱلۡمُقَرَّبُونَ",
      "translation": "yang disaksikan oleh (malaikat-malaikat) yang didekatkan (kepada Allah)"
    },
    {
      "verse": 22,
      "arabic": "إِنَّ ٱلۡأَبۡرَارَ لَفِی نَعِیمٍ",
      "translation": "Sesungguhnya orang-orang yang berbakti benar-benar berada dalam (surga yang penuh) kenikmatan"
    },
    {
      "verse": 23,
      "arabic": "عَلَى ٱلۡأَرَاۤئِكِ یَنظُرُونَ",
      "translation": "mereka (duduk) di atas dipan-dipan melepas pandangan"
    },
    {
      "verse": 24,
      "arabic": "تَعۡرِفُ فِی وُجُوهِهِمۡ نَضۡرَةَ ٱلنَّعِیمِ",
      "translation": "Kamu dapat mengetahui dari wajah mereka kesenangan hidup yang penuh kenikmatan"
    },
    {
      "verse": 25,
      "arabic": "یُسۡقَوۡنَ مِن رَّحِیقࣲ مَّخۡتُومٍ",
      "translation": "Mereka diberi minum dari khamar murni (tidak memabukkan) yang (tempatnya) masih dilak (disegel)"
    },
    {
      "verse": 26,
      "arabic": "خِتَـٰمُهُۥ مِسۡكࣱۚ وَفِی ذَ ٰلِكَ فَلۡیَتَنَافَسِ ٱلۡمُتَنَـٰفِسُونَ",
      "translation": "laknya dari kasturi. Dan untuk yang demikian itu hendaknya orang berlomba-lomba"
    },
    {
      "verse": 27,
      "arabic": "وَمِزَاجُهُۥ مِن تَسۡنِیمٍ",
      "translation": "Dan campurannya dari tasnīm"
    },
    {
      "verse": 28,
      "arabic": "عَیۡنࣰا یَشۡرَبُ بِهَا ٱلۡمُقَرَّبُونَ",
      "translation": "(yaitu) mata air yang diminum oleh mereka yang dekat (kepada Allah)"
    },
    {
      "verse": 29,
      "arabic": "إِنَّ ٱلَّذِینَ أَجۡرَمُوا۟ كَانُوا۟ مِنَ ٱلَّذِینَ ءَامَنُوا۟ یَضۡحَكُونَ",
      "translation": "Sesungguhnya orang-orang yang berdosa, adalah mereka yang dahulu menertawakan orang-orang yang beriman"
    },
    {
      "verse": 30,
      "arabic": "وَإِذَا مَرُّوا۟ بِهِمۡ یَتَغَامَزُونَ",
      "translation": "Dan apabila mereka (orang-orang yang beriman) melintas di hadapan mereka, mereka saling mengedip-ngedipkan matanya"
    },
    {
      "verse": 31,
      "arabic": "وَإِذَا ٱنقَلَبُوۤا۟ إِلَىٰۤ أَهۡلِهِمُ ٱنقَلَبُوا۟ فَكِهِینَ",
      "translation": "dan apabila kembali kepada kaumnya, mereka kembali dengan gembira ria"
    },
    {
      "verse": 32,
      "arabic": "وَإِذَا رَأَوۡهُمۡ قَالُوۤا۟ إِنَّ هَـٰۤؤُلَاۤءِ لَضَاۤلُّونَ",
      "translation": "Dan apabila mereka melihat (orang-orang mukmin), mereka mengatakan, \"Sesungguhnya mereka benar-benar orang-orang sesat"
    },
    {
      "verse": 33,
      "arabic": "وَمَاۤ أُرۡسِلُوا۟ عَلَیۡهِمۡ حَـٰفِظِینَ",
      "translation": "padahal (orang-orang yang berdosa itu), mereka tidak diutus sebagai penjaga (orang-orang mukmin)"
    },
    {
      "verse": 34,
      "arabic": "فَٱلۡیَوۡمَ ٱلَّذِینَ ءَامَنُوا۟ مِنَ ٱلۡكُفَّارِ یَضۡحَكُونَ",
      "translation": "Maka pada hari ini, orang-orang yang beriman yang menertawakan orang-orang kafir"
    },
    {
      "verse": 35,
      "arabic": "عَلَى ٱلۡأَرَاۤئِكِ یَنظُرُونَ",
      "translation": "mereka (duduk) di atas dipan-dipan melepas pandangan"
    },
    {
      "verse": 36,
      "arabic": "هَلۡ ثُوِّبَ ٱلۡكُفَّارُ مَا كَانُوا۟ یَفۡعَلُونَ",
      "translation": "Apakah orang-orang kafir itu diberi balasan (hukuman) terhadap apa yang telah mereka perbuat"
    }
  ],
  "84": [
    {
      "verse": 1,
      "arabic": "۞ إِذَا ٱلسَّمَاۤءُ ٱنشَقَّتۡ",
      "translation": "Apabila langit terbelah"
    },
    {
      "verse": 2,
      "arabic": "وَأَذِنَتۡ لِرَبِّهَا وَحُقَّتۡ",
      "translation": "dan patuh kepada Tuhannya, dan sudah semestinya patuh"
    },
    {
      "verse": 3,
      "arabic": "وَإِذَا ٱلۡأَرۡضُ مُدَّتۡ",
      "translation": "dan apabila bumi diratakan"
    },
    {
      "verse": 4,
      "arabic": "وَأَلۡقَتۡ مَا فِیهَا وَتَخَلَّتۡ",
      "translation": "dan memuntahkan apa yang ada di dalamnya dan menjadi kosong"
    },
    {
      "verse": 5,
      "arabic": "وَأَذِنَتۡ لِرَبِّهَا وَحُقَّتۡ",
      "translation": "dan patuh kepada Tuhannya, dan sudah semestinya patuh"
    },
    {
      "verse": 6,
      "arabic": "یَـٰۤأَیُّهَا ٱلۡإِنسَـٰنُ إِنَّكَ كَادِحٌ إِلَىٰ رَبِّكَ كَدۡحࣰا فَمُلَـٰقِیهِ",
      "translation": "Wahai manusia! Sesungguhnya kamu telah bekerja keras menuju Tuhanmu, maka kamu akan menemui-Nya"
    },
    {
      "verse": 7,
      "arabic": "فَأَمَّا مَنۡ أُوتِیَ كِتَـٰبَهُۥ بِیَمِینِهِۦ",
      "translation": "Maka adapun orang yang catatanya diberikan dari sebelah kanannya"
    },
    {
      "verse": 8,
      "arabic": "فَسَوۡفَ یُحَاسَبُ حِسَابࣰا یَسِیرࣰا",
      "translation": "maka dia akan diperiksa dengan pemeriksaan yang mudah"
    },
    {
      "verse": 9,
      "arabic": "وَیَنقَلِبُ إِلَىٰۤ أَهۡلِهِۦ مَسۡرُورࣰا",
      "translation": "dan dia akan kembali kepada keluarganya (yang sama-sama beriman) dengan gembira"
    },
    {
      "verse": 10,
      "arabic": "وَأَمَّا مَنۡ أُوتِیَ كِتَـٰبَهُۥ وَرَاۤءَ ظَهۡرِهِۦ",
      "translation": "Dan adapun orang yang catatannya diberikan dari arah belakang"
    },
    {
      "verse": 11,
      "arabic": "فَسَوۡفَ یَدۡعُوا۟ ثُبُورࣰا",
      "translation": "maka dia akan berteriak, \"Celakalah aku"
    },
    {
      "verse": 12,
      "arabic": "وَیَصۡلَىٰ سَعِیرًا",
      "translation": "Dan dia akan masuk ke dalam api yang menyala-nyala (neraka)"
    },
    {
      "verse": 13,
      "arabic": "إِنَّهُۥ كَانَ فِیۤ أَهۡلِهِۦ مَسۡرُورًا",
      "translation": "Sungguh, dia dahulu (di dunia) bergembira di kalangan keluarganya (yang sama-sama kafir)"
    },
    {
      "verse": 14,
      "arabic": "إِنَّهُۥ ظَنَّ أَن لَّن یَحُورَ",
      "translation": "Sesungguhnya dia mengira bahwa dia tidak akan kembali (kepada Tuhannya)"
    },
    {
      "verse": 15,
      "arabic": "بَلَىٰۤۚ إِنَّ رَبَّهُۥ كَانَ بِهِۦ بَصِیرࣰا",
      "translation": "Tidak demikian, sesungguhnya Tuhannya selalu melihatnya"
    },
    {
      "verse": 16,
      "arabic": "فَلَاۤ أُقۡسِمُ بِٱلشَّفَقِ",
      "translation": "Maka Aku bersumpah demi cahaya merah pada waktu senja"
    },
    {
      "verse": 17,
      "arabic": "وَٱلَّیۡلِ وَمَا وَسَقَ",
      "translation": "demi malam dan apa yang diselubunginya"
    },
    {
      "verse": 18,
      "arabic": "وَٱلۡقَمَرِ إِذَا ٱتَّسَقَ",
      "translation": "demi bulan apabila jadi purnama"
    },
    {
      "verse": 19,
      "arabic": "لَتَرۡكَبُنَّ طَبَقًا عَن طَبَقࣲ",
      "translation": "sungguh, akan kamu jalani tingkat demi tingkat (dalam kehidupan)"
    },
    {
      "verse": 20,
      "arabic": "فَمَا لَهُمۡ لَا یُؤۡمِنُونَ",
      "translation": "Maka mengapa mereka tidak mau beriman"
    },
    {
      "verse": 21,
      "arabic": "وَإِذَا قُرِئَ عَلَیۡهِمُ ٱلۡقُرۡءَانُ لَا یَ̅سۡ̅جُ̅دُ̅و̅نَ̅ ۩",
      "translation": "Dan apabila Alquran dibacakan kepada mereka, mereka tidak (mau) bersujud"
    },
    {
      "verse": 22,
      "arabic": "بَلِ ٱلَّذِینَ كَفَرُوا۟ یُكَذِّبُونَ",
      "translation": "bahkan orang-orang kafir itu mendustakan-(nya)"
    },
    {
      "verse": 23,
      "arabic": "وَٱللَّهُ أَعۡلَمُ بِمَا یُوعُونَ",
      "translation": "Dan Allah lebih mengetahui apa yang mereka sembunyikan (dalam hati mereka)"
    },
    {
      "verse": 24,
      "arabic": "فَبَشِّرۡهُم بِعَذَابٍ أَلِیمٍ",
      "translation": "Maka sampaikanlah kepada mereka (ancaman) azab yang pedih"
    },
    {
      "verse": 25,
      "arabic": "إِلَّا ٱلَّذِینَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّـٰلِحَـٰتِ لَهُمۡ أَجۡرٌ غَیۡرُ مَمۡنُونِۭ",
      "translation": "kecuali orang-orang yang beriman dan mengerjakan kebajikan, mereka akan mendapat pahala yang tidak putus-putusnya"
    }
  ],
  "85": [
    {
      "verse": 1,
      "arabic": "وَٱلسَّمَاۤءِ ذَاتِ ٱلۡبُرُوجِ",
      "translation": "Demi langit yang mempunyai gugusan bintang"
    },
    {
      "verse": 2,
      "arabic": "وَٱلۡیَوۡمِ ٱلۡمَوۡعُودِ",
      "translation": "dan demi hari yang dijanjikan"
    },
    {
      "verse": 3,
      "arabic": "وَشَاهِدࣲ وَمَشۡهُودࣲ",
      "translation": "Demi yang menyaksikan dan yang disaksikan"
    },
    {
      "verse": 4,
      "arabic": "قُتِلَ أَصۡحَـٰبُ ٱلۡأُخۡدُودِ",
      "translation": "Binasalah orang-orang yang membuat parit (yaitu para pembesar Najran di Yaman)"
    },
    {
      "verse": 5,
      "arabic": "ٱلنَّارِ ذَاتِ ٱلۡوَقُودِ",
      "translation": "yang berapi (yang mempunyai) kayu bakar"
    },
    {
      "verse": 6,
      "arabic": "إِذۡ هُمۡ عَلَیۡهَا قُعُودࣱ",
      "translation": "ketika mereka duduk di sekitarnya"
    },
    {
      "verse": 7,
      "arabic": "وَهُمۡ عَلَىٰ مَا یَفۡعَلُونَ بِٱلۡمُؤۡمِنِینَ شُهُودࣱ",
      "translation": "sedang mereka menyaksikan apa yang mereka perbuat terhadap orang-orang mukmin"
    },
    {
      "verse": 8,
      "arabic": "وَمَا نَقَمُوا۟ مِنۡهُمۡ إِلَّاۤ أَن یُؤۡمِنُوا۟ بِٱللَّهِ ٱلۡعَزِیزِ ٱلۡحَمِیدِ",
      "translation": "Dan mereka menyiksa orang-orang mukmin itu hanya karena (orang-orang mukmin itu) beriman kepada Allah Yang Mahaperkasa, Maha Terpuji"
    },
    {
      "verse": 9,
      "arabic": "ٱلَّذِی لَهُۥ مُلۡكُ ٱلسَّمَـٰوَ ٰتِ وَٱلۡأَرۡضِۚ وَٱللَّهُ عَلَىٰ كُلِّ شَیۡءࣲ شَهِیدٌ",
      "translation": "yang memiliki kerajaan langit dan bumi. Dan Allah Maha Menyaksikan segala sesuatu"
    },
    {
      "verse": 10,
      "arabic": "إِنَّ ٱلَّذِینَ فَتَنُوا۟ ٱلۡمُؤۡمِنِینَ وَٱلۡمُؤۡمِنَـٰتِ ثُمَّ لَمۡ یَتُوبُوا۟ فَلَهُمۡ عَذَابُ جَهَنَّمَ وَلَهُمۡ عَذَابُ ٱلۡحَرِیقِ",
      "translation": "Sungguh, orang-orang yang mendatangkan cobaan (bencana, membunuh, menyiksa) kepada orang-orang mukmin laki-laki dan perempuan lalu mereka tidak bertobat, maka mereka akan mendapat azab Jahanam dan mereka akan mendapat azab (neraka) yang membakar"
    },
    {
      "verse": 11,
      "arabic": "إِنَّ ٱلَّذِینَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّـٰلِحَـٰتِ لَهُمۡ جَنَّـٰتࣱ تَجۡرِی مِن تَحۡتِهَا ٱلۡأَنۡهَـٰرُۚ ذَ ٰلِكَ ٱلۡفَوۡزُ ٱلۡكَبِیرُ",
      "translation": "Sungguh, orang-orang yang beriman dan mengerjakan kebajikan, mereka akan mendapat surga yang mengalir di bawahnya sungai-sungai, itulah kemenangan yang agung"
    },
    {
      "verse": 12,
      "arabic": "إِنَّ بَطۡشَ رَبِّكَ لَشَدِیدٌ",
      "translation": "Sungguh, azab Tuhanmu sangat keras"
    },
    {
      "verse": 13,
      "arabic": "إِنَّهُۥ هُوَ یُبۡدِئُ وَیُعِیدُ",
      "translation": "Sungguh, Dialah yang memulai penciptaan (makhluk) dan yang menghidupkannya (kembali)"
    },
    {
      "verse": 14,
      "arabic": "وَهُوَ ٱلۡغَفُورُ ٱلۡوَدُودُ",
      "translation": "Dan Dialah Yang Maha Pengampun, Maha Pengasih"
    },
    {
      "verse": 15,
      "arabic": "ذُو ٱلۡعَرۡشِ ٱلۡمَجِیدُ",
      "translation": "Yang memiliki Arasy, lagi Mahamulia"
    },
    {
      "verse": 16,
      "arabic": "فَعَّالࣱ لِّمَا یُرِیدُ",
      "translation": "Mahakuasa berbuat apa yang Dia kehendaki"
    },
    {
      "verse": 17,
      "arabic": "هَلۡ أَتَىٰكَ حَدِیثُ ٱلۡجُنُودِ",
      "translation": "Sudahkah sampai kepadamu berita tentang bala tentara (penentang)"
    },
    {
      "verse": 18,
      "arabic": "فِرۡعَوۡنَ وَثَمُودَ",
      "translation": "(yaitu) Fir'aun dan Samud"
    },
    {
      "verse": 19,
      "arabic": "بَلِ ٱلَّذِینَ كَفَرُوا۟ فِی تَكۡذِیبࣲ",
      "translation": "Memang orang-orang kafir (selalu) mendustakan"
    },
    {
      "verse": 20,
      "arabic": "وَٱللَّهُ مِن وَرَاۤئِهِم مُّحِیطُۢ",
      "translation": "padahal Allah mengepung dari belakang mereka (sehingga tidak dapat lolos)"
    },
    {
      "verse": 21,
      "arabic": "بَلۡ هُوَ قُرۡءَانࣱ مَّجِیدࣱ",
      "translation": "Bahkan (yang didustakan itu) ialah Alquran yang mulia"
    },
    {
      "verse": 22,
      "arabic": "فِی لَوۡحࣲ مَّحۡفُوظِۭ",
      "translation": "yang (tersimpan) dalam (tempat) yang terjaga (Lauḥ Maḥfūẓ)"
    }
  ],
  "86": [
    {
      "verse": 1,
      "arabic": "وَٱلسَّمَاۤءِ وَٱلطَّارِقِ",
      "translation": "Demi langit dan yang datang pada malam hari"
    },
    {
      "verse": 2,
      "arabic": "وَمَاۤ أَدۡرَىٰكَ مَا ٱلطَّارِقُ",
      "translation": "Dan tahukah kamu apakah yang datang pada malam hari itu"
    },
    {
      "verse": 3,
      "arabic": "ٱلنَّجۡمُ ٱلثَّاقِبُ",
      "translation": "(Yaitu) bintang yang bersinar tajam"
    },
    {
      "verse": 4,
      "arabic": "إِن كُلُّ نَفۡسࣲ لَّمَّا عَلَیۡهَا حَافِظࣱ",
      "translation": "setiap orang pasti ada penjaganya"
    },
    {
      "verse": 5,
      "arabic": "فَلۡیَنظُرِ ٱلۡإِنسَـٰنُ مِمَّ خُلِقَ",
      "translation": "Maka hendaklah manusia memperhatikan dari apa dia diciptakan"
    },
    {
      "verse": 6,
      "arabic": "خُلِقَ مِن مَّاۤءࣲ دَافِقࣲ",
      "translation": "Dia diciptakan dari air (mani) yang terpancar"
    },
    {
      "verse": 7,
      "arabic": "یَخۡرُجُ مِنۢ بَیۡنِ ٱلصُّلۡبِ وَٱلتَّرَاۤئِبِ",
      "translation": "yang keluar dari antara tulang punggung (sulbi) dan tulang dada"
    },
    {
      "verse": 8,
      "arabic": "إِنَّهُۥ عَلَىٰ رَجۡعِهِۦ لَقَادِرࣱ",
      "translation": "Sungguh, Allah benar-benar kuasa untuk mengembalikannya (hidup setelah mati)"
    },
    {
      "verse": 9,
      "arabic": "یَوۡمَ تُبۡلَى ٱلسَّرَاۤئِرُ",
      "translation": "Pada hari ditampakkan segala rahasia"
    },
    {
      "verse": 10,
      "arabic": "فَمَا لَهُۥ مِن قُوَّةࣲ وَلَا نَاصِرࣲ",
      "translation": "maka manusia tidak lagi mempunyai suatu kekuatan dan tidak (pula) ada penolong"
    },
    {
      "verse": 11,
      "arabic": "وَٱلسَّمَاۤءِ ذَاتِ ٱلرَّجۡعِ",
      "translation": "Demi langit yang mengandung hujan"
    },
    {
      "verse": 12,
      "arabic": "وَٱلۡأَرۡضِ ذَاتِ ٱلصَّدۡعِ",
      "translation": "dan bumi yang mempunyai tumbuh-tumbuhan"
    },
    {
      "verse": 13,
      "arabic": "إِنَّهُۥ لَقَوۡلࣱ فَصۡلࣱ",
      "translation": "sungguh, (Alquran) itu benar-benar firman pemisah (antara yang hak dan yang batil)"
    },
    {
      "verse": 14,
      "arabic": "وَمَا هُوَ بِٱلۡهَزۡلِ",
      "translation": "dan (Alquran) itu bukanlah senda gurauan"
    },
    {
      "verse": 15,
      "arabic": "إِنَّهُمۡ یَكِیدُونَ كَیۡدࣰا",
      "translation": "Sungguh, mereka (orang kafir) merencanakan tipu daya yang jahat"
    },
    {
      "verse": 16,
      "arabic": "وَأَكِیدُ كَیۡدࣰا",
      "translation": "dan Aku pun membuat rencana (tipu daya) yang jitu"
    },
    {
      "verse": 17,
      "arabic": "فَمَهِّلِ ٱلۡكَـٰفِرِینَ أَمۡهِلۡهُمۡ رُوَیۡدَۢا",
      "translation": "Karena itu berilah penangguhan kepada orang-orang kafir. Berilah mereka kesempatan untuk sementara waktu"
    }
  ],
  "87": [
    {
      "verse": 1,
      "arabic": "۞ سَبِّحِ ٱسۡمَ رَبِّكَ ٱلۡأَعۡلَى",
      "translation": "Sucikanlah nama Tuhanmu Yang Mahatinggi"
    },
    {
      "verse": 2,
      "arabic": "ٱلَّذِی خَلَقَ فَسَوَّىٰ",
      "translation": "yang menciptakan, lalu menyempurnakan (penciptaan-Nya)"
    },
    {
      "verse": 3,
      "arabic": "وَٱلَّذِی قَدَّرَ فَهَدَىٰ",
      "translation": "yang menentukan kadar (masing-masing) dan memberi petunjuk"
    },
    {
      "verse": 4,
      "arabic": "وَٱلَّذِیۤ أَخۡرَجَ ٱلۡمَرۡعَىٰ",
      "translation": "dan Yang menumbuhkan rerumputan"
    },
    {
      "verse": 5,
      "arabic": "فَجَعَلَهُۥ غُثَاۤءً أَحۡوَىٰ",
      "translation": "lalu dijadikan-Nya (rumput-rumput) itu kering kehitam-hitaman"
    },
    {
      "verse": 6,
      "arabic": "سَنُقۡرِئُكَ فَلَا تَنسَىٰۤ",
      "translation": "Kami akan membacakan (Alquran) kepadamu (Muhammad) sehingga engkau tidak akan lupa"
    },
    {
      "verse": 7,
      "arabic": "إِلَّا مَا شَاۤءَ ٱللَّهُۚ إِنَّهُۥ یَعۡلَمُ ٱلۡجَهۡرَ وَمَا یَخۡفَىٰ",
      "translation": "kecuali jika Allah menghendaki. Sungguh, Dia mengetahui yang terang dan yang tersembunyi"
    },
    {
      "verse": 8,
      "arabic": "وَنُیَسِّرُكَ لِلۡیُسۡرَىٰ",
      "translation": "Dan Kami akan memudahkan bagimu ke jalan kemudahan (mencapai kebahagian dunia dan akhirat)"
    },
    {
      "verse": 9,
      "arabic": "فَذَكِّرۡ إِن نَّفَعَتِ ٱلذِّكۡرَىٰ",
      "translation": "oleh sebab itu berikanlah peringatan, karena peringatan itu bermanfaat"
    },
    {
      "verse": 10,
      "arabic": "سَیَذَّكَّرُ مَن یَخۡشَىٰ",
      "translation": "orang yang takut (kepada Allah) akan mendapat pelajaran"
    },
    {
      "verse": 11,
      "arabic": "وَیَتَجَنَّبُهَا ٱلۡأَشۡقَى",
      "translation": "dan orang yang celaka (kafir) akan menjauhinya"
    },
    {
      "verse": 12,
      "arabic": "ٱلَّذِی یَصۡلَى ٱلنَّارَ ٱلۡكُبۡرَىٰ",
      "translation": "(yaitu) orang yang akan memasuki api yang besar (neraka)"
    },
    {
      "verse": 13,
      "arabic": "ثُمَّ لَا یَمُوتُ فِیهَا وَلَا یَحۡیَىٰ",
      "translation": "selanjutnya dia di sana tidak mati dan tidak (pula) hidup"
    },
    {
      "verse": 14,
      "arabic": "قَدۡ أَفۡلَحَ مَن تَزَكَّىٰ",
      "translation": "Sungguh beruntung orang yang menyucikan diri (dengan beriman)"
    },
    {
      "verse": 15,
      "arabic": "وَذَكَرَ ٱسۡمَ رَبِّهِۦ فَصَلَّىٰ",
      "translation": "dan mengingat nama Tuhannya, lalu dia salat"
    },
    {
      "verse": 16,
      "arabic": "بَلۡ تُؤۡثِرُونَ ٱلۡحَیَوٰةَ ٱلدُّنۡیَا",
      "translation": "Sedangkan kamu (orang-orang kafir) memilih kehidupan dunia"
    },
    {
      "verse": 17,
      "arabic": "وَٱلۡءَاخِرَةُ خَیۡرࣱ وَأَبۡقَىٰۤ",
      "translation": "padahal kehidupan akhirat itu lebih baik dan lebih kekal"
    },
    {
      "verse": 18,
      "arabic": "إِنَّ هَـٰذَا لَفِی ٱلصُّحُفِ ٱلۡأُولَىٰ",
      "translation": "Sesungguhnya ini terdapat dalam kitab-kitab yang dahulu"
    },
    {
      "verse": 19,
      "arabic": "صُحُفِ إِبۡرَ ٰهِیمَ وَمُوسَىٰ",
      "translation": "(yaitu) kitab-kitab Ibrahim dan Musa"
    }
  ],
  "88": [
    {
      "verse": 1,
      "arabic": "هَلۡ أَتَىٰكَ حَدِیثُ ٱلۡغَـٰشِیَةِ",
      "translation": "Sudahkah sampai kepadamu berita tentang (hari Kiamat)"
    },
    {
      "verse": 2,
      "arabic": "وُجُوهࣱ یَوۡمَئِذٍ خَـٰشِعَةٌ",
      "translation": "Pada hari itu banyak wajah yang tertunduk hina"
    },
    {
      "verse": 3,
      "arabic": "عَامِلَةࣱ نَّاصِبَةࣱ",
      "translation": "(karena) bekerja keras lagi kepayahan"
    },
    {
      "verse": 4,
      "arabic": "تَصۡلَىٰ نَارًا حَامِیَةࣰ",
      "translation": "mereka memasuki api yang sangat panas (neraka)"
    },
    {
      "verse": 5,
      "arabic": "تُسۡقَىٰ مِنۡ عَیۡنٍ ءَانِیَةࣲ",
      "translation": "diberi minum dari sumber mata air yang sangat panas"
    },
    {
      "verse": 6,
      "arabic": "لَّیۡسَ لَهُمۡ طَعَامٌ إِلَّا مِن ضَرِیعࣲ",
      "translation": "Tidak ada makanan bagi mereka selain dari pohon yang berduri"
    },
    {
      "verse": 7,
      "arabic": "لَّا یُسۡمِنُ وَلَا یُغۡنِی مِن جُوعࣲ",
      "translation": "yang tidak menggemukkan dan tidak menghilangkan lapar"
    },
    {
      "verse": 8,
      "arabic": "وُجُوهࣱ یَوۡمَئِذࣲ نَّاعِمَةࣱ",
      "translation": "Pada hari itu banyak (pula) wajah yang berseri-seri"
    },
    {
      "verse": 9,
      "arabic": "لِّسَعۡیِهَا رَاضِیَةࣱ",
      "translation": "merasa senang karena usahanya (sendiri)"
    },
    {
      "verse": 10,
      "arabic": "فِی جَنَّةٍ عَالِیَةࣲ",
      "translation": "(mereka) dalam surga yang tinggi"
    },
    {
      "verse": 11,
      "arabic": "لَّا تَسۡمَعُ فِیهَا لَـٰغِیَةࣰ",
      "translation": "di sana (kamu) tidak mendengar perkataan yang tidak berguna"
    },
    {
      "verse": 12,
      "arabic": "فِیهَا عَیۡنࣱ جَارِیَةࣱ",
      "translation": "Di sana ada mata air yang mengalir"
    },
    {
      "verse": 13,
      "arabic": "فِیهَا سُرُرࣱ مَّرۡفُوعَةࣱ",
      "translation": "Di sana ada dipan-dipan yang ditinggikan"
    },
    {
      "verse": 14,
      "arabic": "وَأَكۡوَابࣱ مَّوۡضُوعَةࣱ",
      "translation": "dan gelas-gelas yang tersedia (di dekatnya)"
    },
    {
      "verse": 15,
      "arabic": "وَنَمَارِقُ مَصۡفُوفَةࣱ",
      "translation": "dan bantal-bantal sandaran yang tersusun"
    },
    {
      "verse": 16,
      "arabic": "وَزَرَابِیُّ مَبۡثُوثَةٌ",
      "translation": "dan permadani-permadani yang terhampar"
    },
    {
      "verse": 17,
      "arabic": "أَفَلَا یَنظُرُونَ إِلَى ٱلۡإِبِلِ كَیۡفَ خُلِقَتۡ",
      "translation": "Maka tidakkah mereka memperhatikan unta, bagaimana diciptakan"
    },
    {
      "verse": 18,
      "arabic": "وَإِلَى ٱلسَّمَاۤءِ كَیۡفَ رُفِعَتۡ",
      "translation": "Dan langit, bagaimana ditinggikan"
    },
    {
      "verse": 19,
      "arabic": "وَإِلَى ٱلۡجِبَالِ كَیۡفَ نُصِبَتۡ",
      "translation": "Dan gunung-gunung bagaimana ditegakkan"
    },
    {
      "verse": 20,
      "arabic": "وَإِلَى ٱلۡأَرۡضِ كَیۡفَ سُطِحَتۡ",
      "translation": "Dan bumi bagaimana dihamparkan"
    },
    {
      "verse": 21,
      "arabic": "فَذَكِّرۡ إِنَّمَاۤ أَنتَ مُذَكِّرࣱ",
      "translation": "Maka berilah peringatan, karena sesungguhnya engkau (Muhammad) hanyalah pemberi peringatan"
    },
    {
      "verse": 22,
      "arabic": "لَّسۡتَ عَلَیۡهِم بِمُصَۣیۡطِرٍ",
      "translation": "Engkau bukanlah orang yang berkuasa atas mereka"
    },
    {
      "verse": 23,
      "arabic": "إِلَّا مَن تَوَلَّىٰ وَكَفَرَ",
      "translation": "kecuali (jika ada) orang yang berpaling dan kafir"
    },
    {
      "verse": 24,
      "arabic": "فَیُعَذِّبُهُ ٱللَّهُ ٱلۡعَذَابَ ٱلۡأَكۡبَرَ",
      "translation": "maka Allah akan mengazabnya dengan azab yang besar"
    },
    {
      "verse": 25,
      "arabic": "إِنَّ إِلَیۡنَاۤ إِیَابَهُمۡ",
      "translation": "Sungguh, kepada Kami lah mereka kembali"
    },
    {
      "verse": 26,
      "arabic": "ثُمَّ إِنَّ عَلَیۡنَا حِسَابَهُم",
      "translation": "kemudian sesungguhnya (kewajiban) Kami lah membuat perhitungan atas mereka"
    }
  ],
  "89": [
    {
      "verse": 1,
      "arabic": "وَٱلۡفَجۡرِ",
      "translation": "Demi fajar"
    },
    {
      "verse": 2,
      "arabic": "وَلَیَالٍ عَشۡرࣲ",
      "translation": "demi malam yang sepuluh"
    },
    {
      "verse": 3,
      "arabic": "وَٱلشَّفۡعِ وَٱلۡوَتۡرِ",
      "translation": "demi yang genap dan yang ganjil"
    },
    {
      "verse": 4,
      "arabic": "وَٱلَّیۡلِ إِذَا یَسۡرِ",
      "translation": "demi malam apabila berlalu"
    },
    {
      "verse": 5,
      "arabic": "هَلۡ فِی ذَ ٰلِكَ قَسَمࣱ لِّذِی حِجۡرٍ",
      "translation": "Adakah pada yang demikian itu terdapat sumpah (yang dapat diterima) bagi orang-orang yang berakal"
    },
    {
      "verse": 6,
      "arabic": "أَلَمۡ تَرَ كَیۡفَ فَعَلَ رَبُّكَ بِعَادٍ",
      "translation": "Tidakkah engkau (Muhammad) memperhatikan bagaimana Tuhanmu berbuat terhadap (kaum) 'Ād"
    },
    {
      "verse": 7,
      "arabic": "إِرَمَ ذَاتِ ٱلۡعِمَادِ",
      "translation": "(yaitu) penduduk Iram (ibukota kaum 'Ād) yang mempunyai bangunan-bangunan yang tinggi"
    },
    {
      "verse": 8,
      "arabic": "ٱلَّتِی لَمۡ یُخۡلَقۡ مِثۡلُهَا فِی ٱلۡبِلَـٰدِ",
      "translation": "yang belum pernah dibangun (suatu kota) seperti itu, di negeri-negeri lain"
    },
    {
      "verse": 9,
      "arabic": "وَثَمُودَ ٱلَّذِینَ جَابُوا۟ ٱلصَّخۡرَ بِٱلۡوَادِ",
      "translation": "dan (terhadap) kaum Samud yang memotong batu-batu besar di lembah"
    },
    {
      "verse": 10,
      "arabic": "وَفِرۡعَوۡنَ ذِی ٱلۡأَوۡتَادِ",
      "translation": "dan (terhadap) Fir'aun yang mempunyai pasak-pasak (bangunan yang besar)"
    },
    {
      "verse": 11,
      "arabic": "ٱلَّذِینَ طَغَوۡا۟ فِی ٱلۡبِلَـٰدِ",
      "translation": "yang berbuat sewenang-wenang dalam negeri"
    },
    {
      "verse": 12,
      "arabic": "فَأَكۡثَرُوا۟ فِیهَا ٱلۡفَسَادَ",
      "translation": "lalu mereka banyak berbuat kerusakan dalam negeri itu"
    },
    {
      "verse": 13,
      "arabic": "فَصَبَّ عَلَیۡهِمۡ رَبُّكَ سَوۡطَ عَذَابٍ",
      "translation": "karena itu Tuhanmu menimpakan cemeti azab kepada mereka"
    },
    {
      "verse": 14,
      "arabic": "إِنَّ رَبَّكَ لَبِٱلۡمِرۡصَادِ",
      "translation": "sungguh, Tuhanmu benar-benar mengawasi"
    },
    {
      "verse": 15,
      "arabic": "فَأَمَّا ٱلۡإِنسَـٰنُ إِذَا مَا ٱبۡتَلَىٰهُ رَبُّهُۥ فَأَكۡرَمَهُۥ وَنَعَّمَهُۥ فَیَقُولُ رَبِّیۤ أَكۡرَمَنِ",
      "translation": "Adapun manusia, apabila Tuhan mengujinya lalu memuliakannya dan memberinya kesenangan, maka dia berkata, \"Tuhanku telah memuliakanku"
    },
    {
      "verse": 16,
      "arabic": "وَأَمَّاۤ إِذَا مَا ٱبۡتَلَىٰهُ فَقَدَرَ عَلَیۡهِ رِزۡقَهُۥ فَیَقُولُ رَبِّیۤ أَهَـٰنَنِ",
      "translation": "Namun apabila Tuhan mengujinya lalu membatasi rezekinya, maka dia berkata, \"Tuhanku telah menghinaku"
    },
    {
      "verse": 17,
      "arabic": "كَلَّاۖ بَل لَّا تُكۡرِمُونَ ٱلۡیَتِیمَ",
      "translation": "Sekali-kali tidak! Bahkan kamu tidak memuliakan anak yatim"
    },
    {
      "verse": 18,
      "arabic": "وَلَا تَحَـٰۤضُّونَ عَلَىٰ طَعَامِ ٱلۡمِسۡكِینِ",
      "translation": "dan kamu tidak saling mengajak memberi makan orang miskin"
    },
    {
      "verse": 19,
      "arabic": "وَتَأۡكُلُونَ ٱلتُّرَاثَ أَكۡلࣰا لَّمࣰّا",
      "translation": "sedangkan kamu memakan harta warisan dengan cara mencampurbaurkan (yang halal dan yang haram)"
    },
    {
      "verse": 20,
      "arabic": "وَتُحِبُّونَ ٱلۡمَالَ حُبࣰّا جَمࣰّا",
      "translation": "dan kamu mencintai harta dengan kecintaan yang berlebihan"
    },
    {
      "verse": 21,
      "arabic": "كَلَّاۤۖ إِذَا دُكَّتِ ٱلۡأَرۡضُ دَكࣰّا دَكࣰّا",
      "translation": "Sekali-kali tidak! Apabila bumi diguncangkan berturut-turut (berbenturan)"
    },
    {
      "verse": 22,
      "arabic": "وَجَاۤءَ رَبُّكَ وَٱلۡمَلَكُ صَفࣰّا صَفࣰّا",
      "translation": "dan datanglah Tuhanmu; dan malaikat berbaris-baris"
    },
    {
      "verse": 23,
      "arabic": "وَجِا۟یۤءَ یَوۡمَئِذِۭ بِجَهَنَّمَۚ یَوۡمَئِذࣲ یَتَذَكَّرُ ٱلۡإِنسَـٰنُ وَأَنَّىٰ لَهُ ٱلذِّكۡرَىٰ",
      "translation": "dan pada hari itu diperlihatkan neraka Jahanam; pada hari itu sadarlah manusia, tetapi tidak berguna lagi baginya kesadaran itu"
    },
    {
      "verse": 24,
      "arabic": "یَقُولُ یَـٰلَیۡتَنِی قَدَّمۡتُ لِحَیَاتِی",
      "translation": "Dia berkata, \"Alangkah baiknya sekiranya dahulu aku mengerjakan (kebajikan) untuk hidupku ini"
    },
    {
      "verse": 25,
      "arabic": "فَیَوۡمَئِذࣲ لَّا یُعَذِّبُ عَذَابَهُۥۤ أَحَدࣱ",
      "translation": "Maka pada hari itu tidak ada seorang pun yang mengazab seperti azab-Nya (yang adil)"
    },
    {
      "verse": 26,
      "arabic": "وَلَا یُوثِقُ وَثَاقَهُۥۤ أَحَدࣱ",
      "translation": "dan tidak ada seorang pun yang mengikat seperti ikatan-Nya"
    },
    {
      "verse": 27,
      "arabic": "یَـٰۤأَیَّتُهَا ٱلنَّفۡسُ ٱلۡمُطۡمَئِنَّةُ",
      "translation": "Wahai jiwa yang tenang"
    },
    {
      "verse": 28,
      "arabic": "ٱرۡجِعِیۤ إِلَىٰ رَبِّكِ رَاضِیَةࣰ مَّرۡضِیَّةࣰ",
      "translation": "Kembalilah kepada Tuhanmu dengan hati yang rida dan diridai-Nya"
    },
    {
      "verse": 29,
      "arabic": "فَٱدۡخُلِی فِی عِبَـٰدِی",
      "translation": "Maka masuklah ke dalam golongan hamba-hamba-Ku"
    },
    {
      "verse": 30,
      "arabic": "وَٱدۡخُلِی جَنَّتِی",
      "translation": "dan masuklah ke dalam surga-Ku"
    }
  ],
  "90": [
    {
      "verse": 1,
      "arabic": "۞ لَاۤ أُقۡسِمُ بِهَـٰذَا ٱلۡبَلَدِ",
      "translation": "Aku bersumpah dengan negeri ini (Mekkah)"
    },
    {
      "verse": 2,
      "arabic": "وَأَنتَ حِلُّۢ بِهَـٰذَا ٱلۡبَلَدِ",
      "translation": "dan engkau (Muhammad), bertempat di negeri (Mekkah) ini"
    },
    {
      "verse": 3,
      "arabic": "وَوَالِدࣲ وَمَا وَلَدَ",
      "translation": "dan demi (pertalian) bapak dan anaknya"
    },
    {
      "verse": 4,
      "arabic": "لَقَدۡ خَلَقۡنَا ٱلۡإِنسَـٰنَ فِی كَبَدٍ",
      "translation": "Sungguh, Kami telah menciptakan manusia berada dalam susah payah"
    },
    {
      "verse": 5,
      "arabic": "أَیَحۡسَبُ أَن لَّن یَقۡدِرَ عَلَیۡهِ أَحَدࣱ",
      "translation": "Apakah dia (manusia) itu mengira bahwa tidak ada sesuatu pun yang berkuasa atasnya"
    },
    {
      "verse": 6,
      "arabic": "یَقُولُ أَهۡلَكۡتُ مَالࣰا لُّبَدًا",
      "translation": "Dia mengatakan, \"Aku telah menghabiskan harta yang banyak"
    },
    {
      "verse": 7,
      "arabic": "أَیَحۡسَبُ أَن لَّمۡ یَرَهُۥۤ أَحَدٌ",
      "translation": "Apakah dia mengira bahwa tidak ada sesuatu pun yang melihatnya"
    },
    {
      "verse": 8,
      "arabic": "أَلَمۡ نَجۡعَل لَّهُۥ عَیۡنَیۡنِ",
      "translation": "Bukankah Kami telah menjadikan untuknya sepasang mata"
    },
    {
      "verse": 9,
      "arabic": "وَلِسَانࣰا وَشَفَتَیۡنِ",
      "translation": "dan lidah dan sepasang bibir"
    },
    {
      "verse": 10,
      "arabic": "وَهَدَیۡنَـٰهُ ٱلنَّجۡدَیۡنِ",
      "translation": "Dan Kami telah menunjukkan kepadanya dua jalan (kebajikkan dan kejahatan)"
    },
    {
      "verse": 11,
      "arabic": "فَلَا ٱقۡتَحَمَ ٱلۡعَقَبَةَ",
      "translation": "Tetapi dia tidak menempuh jalan yang mendaki dan sukar"
    },
    {
      "verse": 12,
      "arabic": "وَمَاۤ أَدۡرَىٰكَ مَا ٱلۡعَقَبَةُ",
      "translation": "Dan tahukah kamu apakah jalan yang mendaki dan sukar itu"
    },
    {
      "verse": 13,
      "arabic": "فَكُّ رَقَبَةٍ",
      "translation": "(Yaitu) membebaskan budak (hamba sahaya)"
    },
    {
      "verse": 14,
      "arabic": "أَوۡ إِطۡعَـٰمࣱ فِی یَوۡمࣲ ذِی مَسۡغَبَةࣲ",
      "translation": "atau memberi makan pada hari terjadi kelaparan"
    },
    {
      "verse": 15,
      "arabic": "یَتِیمࣰا ذَا مَقۡرَبَةٍ",
      "translation": "(kepada) anak yatim yang ada hubungan kerabat"
    },
    {
      "verse": 16,
      "arabic": "أَوۡ مِسۡكِینࣰا ذَا مَتۡرَبَةࣲ",
      "translation": "atau orang miskin yang sangat fakir"
    },
    {
      "verse": 17,
      "arabic": "ثُمَّ كَانَ مِنَ ٱلَّذِینَ ءَامَنُوا۟ وَتَوَاصَوۡا۟ بِٱلصَّبۡرِ وَتَوَاصَوۡا۟ بِٱلۡمَرۡحَمَةِ",
      "translation": "Kemudian dia termasuk orang-orang yang beriman, dan saling berpesan untuk bersabar dan saling berpesan untuk berkasih sayang"
    },
    {
      "verse": 18,
      "arabic": "أُو۟لَـٰۤئِكَ أَصۡحَـٰبُ ٱلۡمَیۡمَنَةِ",
      "translation": "Mereka (orang-orang yang beriman dan saling berpesan itu) adalah golongan kanan"
    },
    {
      "verse": 19,
      "arabic": "وَٱلَّذِینَ كَفَرُوا۟ بِءَایَـٰتِنَا هُمۡ أَصۡحَـٰبُ ٱلۡمَشۡءَمَةِ",
      "translation": "Dan orang-orang yang kafir kepada ayat-ayat Kami, mereka itu adalah golongan kiri"
    },
    {
      "verse": 20,
      "arabic": "عَلَیۡهِمۡ نَارࣱ مُّؤۡصَدَةُۢ",
      "translation": "Mereka berada dalam neraka yang ditutup rapat"
    }
  ],
  "91": [
    {
      "verse": 1,
      "arabic": "وَٱلشَّمۡسِ وَضُحَىٰهَا",
      "translation": "Demi matahari dan sinarnya pada pagi hari"
    },
    {
      "verse": 2,
      "arabic": "وَٱلۡقَمَرِ إِذَا تَلَىٰهَا",
      "translation": "demi bulan apabila mengiringinya"
    },
    {
      "verse": 3,
      "arabic": "وَٱلنَّهَارِ إِذَا جَلَّىٰهَا",
      "translation": "demi siang apabila menampakkannya"
    },
    {
      "verse": 4,
      "arabic": "وَٱلَّیۡلِ إِذَا یَغۡشَىٰهَا",
      "translation": "demi malam apabila menutupinya (gelap gulita)"
    },
    {
      "verse": 5,
      "arabic": "وَٱلسَّمَاۤءِ وَمَا بَنَىٰهَا",
      "translation": "demi langit serta perancangannya (yang menakjubkan)"
    },
    {
      "verse": 6,
      "arabic": "وَٱلۡأَرۡضِ وَمَا طَحَىٰهَا",
      "translation": "demi bumi serta penghamparannya"
    },
    {
      "verse": 7,
      "arabic": "وَنَفۡسࣲ وَمَا سَوَّىٰهَا",
      "translation": "demi jiwa serta penyempurnaan (ciptaan)nya"
    },
    {
      "verse": 8,
      "arabic": "فَأَلۡهَمَهَا فُجُورَهَا وَتَقۡوَىٰهَا",
      "translation": "maka Dia mengilhamkan kepadanya (jalan) kejahatan dan ketakwaannya"
    },
    {
      "verse": 9,
      "arabic": "قَدۡ أَفۡلَحَ مَن زَكَّىٰهَا",
      "translation": "sungguh beruntung orang yang menyucikannya (jiwa itu)"
    },
    {
      "verse": 10,
      "arabic": "وَقَدۡ خَابَ مَن دَسَّىٰهَا",
      "translation": "dan sungguh rugi orang yang mengotorinya"
    },
    {
      "verse": 11,
      "arabic": "كَذَّبَتۡ ثَمُودُ بِطَغۡوَىٰهَاۤ",
      "translation": "(Kaum) Samud telah mendustakan (rasulnya) karena mereka melampaui batas (zalim)"
    },
    {
      "verse": 12,
      "arabic": "إِذِ ٱنۢبَعَثَ أَشۡقَىٰهَا",
      "translation": "ketika bangkit orang yang paling celaka di antara mereka"
    },
    {
      "verse": 13,
      "arabic": "فَقَالَ لَهُمۡ رَسُولُ ٱللَّهِ نَاقَةَ ٱللَّهِ وَسُقۡیَـٰهَا",
      "translation": "lalu Rasul Allah (Saleh) berkata kepada mereka, \"(Biarkanlah) unta betina dari Allah ini dengan minumannya"
    },
    {
      "verse": 14,
      "arabic": "فَكَذَّبُوهُ فَعَقَرُوهَا فَدَمۡدَمَ عَلَیۡهِمۡ رَبُّهُم بِذَنۢبِهِمۡ فَسَوَّىٰهَا",
      "translation": "Namun mereka mendustakannya dan menyembelihnya, karena itu Tuhan membinasakan mereka karena dosanya, lalu diratakan-Nya (dengan tanah)"
    },
    {
      "verse": 15,
      "arabic": "وَلَا یَخَافُ عُقۡبَـٰهَا",
      "translation": "Dan Dia tidak takut terhadap akibatnya"
    }
  ],
  "92": [
    {
      "verse": 1,
      "arabic": "وَٱلَّیۡلِ إِذَا یَغۡشَىٰ",
      "translation": "Demi malam apabila menutupi (cahaya siang)"
    },
    {
      "verse": 2,
      "arabic": "وَٱلنَّهَارِ إِذَا تَجَلَّىٰ",
      "translation": "demi siang bila terang benderang"
    },
    {
      "verse": 3,
      "arabic": "وَمَا خَلَقَ ٱلذَّكَرَ وَٱلۡأُنثَىٰۤ",
      "translation": "demi penciptaan laki-laki dan perempuan"
    },
    {
      "verse": 4,
      "arabic": "إِنَّ سَعۡیَكُمۡ لَشَتَّىٰ",
      "translation": "sungguh, usahamu memang beraneka macam"
    },
    {
      "verse": 5,
      "arabic": "فَأَمَّا مَنۡ أَعۡطَىٰ وَٱتَّقَىٰ",
      "translation": "Maka barangsiapa memberikan (hartanya di jalan Allah) dan bertakwa"
    },
    {
      "verse": 6,
      "arabic": "وَصَدَّقَ بِٱلۡحُسۡنَىٰ",
      "translation": "dan membenarkan (adanya pahala) yang terbaik (surga)"
    },
    {
      "verse": 7,
      "arabic": "فَسَنُیَسِّرُهُۥ لِلۡیُسۡرَىٰ",
      "translation": "maka akan Kami mudahkan baginya jalan menuju kemudahan (kebahagiaan)"
    },
    {
      "verse": 8,
      "arabic": "وَأَمَّا مَنۢ بَخِلَ وَٱسۡتَغۡنَىٰ",
      "translation": "Dan adapun orang yang kikir dan merasa dirinya cukup (tidak perlu pertolongan Allah)"
    },
    {
      "verse": 9,
      "arabic": "وَكَذَّبَ بِٱلۡحُسۡنَىٰ",
      "translation": "serta mendustakan (pahala) yang terbaik"
    },
    {
      "verse": 10,
      "arabic": "فَسَنُیَسِّرُهُۥ لِلۡعُسۡرَىٰ",
      "translation": "maka akan Kami mudahkan baginya jalan menuju kesukaran (kesengsaraan)"
    },
    {
      "verse": 11,
      "arabic": "وَمَا یُغۡنِی عَنۡهُ مَالُهُۥۤ إِذَا تَرَدَّىٰۤ",
      "translation": "Dan hartanya tidak bermanfaat baginya apabila dia telah binasa"
    },
    {
      "verse": 12,
      "arabic": "إِنَّ عَلَیۡنَا لَلۡهُدَىٰ",
      "translation": "Sesungguhnya Kami lah yang memberi petunjuk"
    },
    {
      "verse": 13,
      "arabic": "وَإِنَّ لَنَا لَلۡءَاخِرَةَ وَٱلۡأُولَىٰ",
      "translation": "dan sesungguhnya milik Kami lah akhirat dan dunia"
    },
    {
      "verse": 14,
      "arabic": "فَأَنذَرۡتُكُمۡ نَارࣰا تَلَظَّىٰ",
      "translation": "Maka aku memperingatkan kamu dengan neraka yang menyala-nyala"
    },
    {
      "verse": 15,
      "arabic": "لَا یَصۡلَىٰهَاۤ إِلَّا ٱلۡأَشۡقَى",
      "translation": "yang hanya dimasuki oleh orang yang paling celaka"
    },
    {
      "verse": 16,
      "arabic": "ٱلَّذِی كَذَّبَ وَتَوَلَّىٰ",
      "translation": "yang mendustakan (kebenaran) dan berpaling (dari iman)"
    },
    {
      "verse": 17,
      "arabic": "وَسَیُجَنَّبُهَا ٱلۡأَتۡقَى",
      "translation": "Dan akan dijauhkan darinya (neraka) orang yang paling bertakwa"
    },
    {
      "verse": 18,
      "arabic": "ٱلَّذِی یُؤۡتِی مَالَهُۥ یَتَزَكَّىٰ",
      "translation": "yang menginfakkan hartanya (di jalan Allah) untuk membersihkan (dirinya)"
    },
    {
      "verse": 19,
      "arabic": "وَمَا لِأَحَدٍ عِندَهُۥ مِن نِّعۡمَةࣲ تُجۡزَىٰۤ",
      "translation": "dan tidak ada seorang pun memberikan suatu nikmat padanya yang harus dibalasnya"
    },
    {
      "verse": 20,
      "arabic": "إِلَّا ٱبۡتِغَاۤءَ وَجۡهِ رَبِّهِ ٱلۡأَعۡلَىٰ",
      "translation": "tetapi (dia memberikan itu semata-mata) karena mencari keridaan Tuhannya Yang Mahatinggi"
    },
    {
      "verse": 21,
      "arabic": "وَلَسَوۡفَ یَرۡضَىٰ",
      "translation": "Dan niscaya kelak dia akan mendapat kesenangan (yang sempurna)"
    }
  ],
  "93": [
    {
      "verse": 1,
      "arabic": "وَٱلضُّحَىٰ",
      "translation": "Demi waktu duha (ketika matahari naik sepenggalan)"
    },
    {
      "verse": 2,
      "arabic": "وَٱلَّیۡلِ إِذَا سَجَىٰ",
      "translation": "dan demi malam apabila telah sunyi"
    },
    {
      "verse": 3,
      "arabic": "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ",
      "translation": "Tuhanmu tidak meninggalkan engkau (Muhammad) dan tidak (pula) membencimu"
    },
    {
      "verse": 4,
      "arabic": "وَلَلۡءَاخِرَةُ خَیۡرࣱ لَّكَ مِنَ ٱلۡأُولَىٰ",
      "translation": "dan sungguh, yang kemudian itu lebih baik bagimu daripada yang permulaan"
    },
    {
      "verse": 5,
      "arabic": "وَلَسَوۡفَ یُعۡطِیكَ رَبُّكَ فَتَرۡضَىٰۤ",
      "translation": "Dan sungguh, kelak Tuhanmu pasti memberikan karunia-Nya kepadamu, sehingga engkau menjadi puas"
    },
    {
      "verse": 6,
      "arabic": "أَلَمۡ یَجِدۡكَ یَتِیمࣰا فَءَاوَىٰ",
      "translation": "Bukankah Dia mendapatimu sebagai seorang yatim, lalu Dia melindungi(mu)"
    },
    {
      "verse": 7,
      "arabic": "وَوَجَدَكَ ضَاۤلࣰّا فَهَدَىٰ",
      "translation": "(Dan Dia mendapatimu sebagai seorang yang bingung,912) lalu Dia memberikan petunjuk"
    },
    {
      "verse": 8,
      "arabic": "وَوَجَدَكَ عَاۤئِلࣰا فَأَغۡنَىٰ",
      "translation": "Dan Dia mendapatimu sebagai seorang yang kekurangan, lalu Dia memberikan kecukupan"
    },
    {
      "verse": 9,
      "arabic": "فَأَمَّا ٱلۡیَتِیمَ فَلَا تَقۡهَرۡ",
      "translation": "Maka terhadap anak yatim janganlah engkau berlaku sewenang-wenang"
    },
    {
      "verse": 10,
      "arabic": "وَأَمَّا ٱلسَّاۤئِلَ فَلَا تَنۡهَرۡ",
      "translation": "Dan terhadap orang yang meminta-minta, janganlah engkau menghardik(nya)"
    },
    {
      "verse": 11,
      "arabic": "وَأَمَّا بِنِعۡمَةِ رَبِّكَ فَحَدِّثۡ",
      "translation": "Dan terhadap nikmat Tuhanmu, hendaklah engkau nyatakan (dengan bersyukur)"
    }
  ],
  "94": [
    {
      "verse": 1,
      "arabic": "۞ أَلَمۡ نَشۡرَحۡ لَكَ صَدۡرَكَ",
      "translation": "Bukankah kami telah melapangkan dadamu (Muhammad)"
    },
    {
      "verse": 2,
      "arabic": "وَوَضَعۡنَا عَنكَ وِزۡرَكَ",
      "translation": "dan kami pun telah menurunkan beban darimu"
    },
    {
      "verse": 3,
      "arabic": "ٱلَّذِیۤ أَنقَضَ ظَهۡرَكَ",
      "translation": "yang memberatkan punggungmu"
    },
    {
      "verse": 4,
      "arabic": "وَرَفَعۡنَا لَكَ ذِكۡرَكَ",
      "translation": "dan kami tinggikan sebutan (nama)mu914) bagimu"
    },
    {
      "verse": 5,
      "arabic": "فَإِنَّ مَعَ ٱلۡعُسۡرِ یُسۡرًا",
      "translation": "Maka sesungguhnya bersama kesulitan ada kemudahan"
    },
    {
      "verse": 6,
      "arabic": "إِنَّ مَعَ ٱلۡعُسۡرِ یُسۡرࣰا",
      "translation": "sesungguhnya bersama kesulitan ada kemudahan"
    },
    {
      "verse": 7,
      "arabic": "فَإِذَا فَرَغۡتَ فَٱنصَبۡ",
      "translation": "Maka apabila engkau telah selesai (dari suatu urusan), tetaplah bekerja keras (untuk urusan yang lain)"
    },
    {
      "verse": 8,
      "arabic": "وَإِلَىٰ رَبِّكَ فَٱرۡغَب",
      "translation": "dan hanya kepada Tuhanmulah engkau berharap"
    }
  ],
  "95": [
    {
      "verse": 1,
      "arabic": "وَٱلتِّینِ وَٱلزَّیۡتُونِ",
      "translation": "Demi (buah) Tin dan (buah) Zaitun"
    },
    {
      "verse": 2,
      "arabic": "وَطُورِ سِینِینَ",
      "translation": "demi gunung Sinai"
    },
    {
      "verse": 3,
      "arabic": "وَهَـٰذَا ٱلۡبَلَدِ ٱلۡأَمِینِ",
      "translation": "dan demi negeri (Mekkah) yang aman ini"
    },
    {
      "verse": 4,
      "arabic": "لَقَدۡ خَلَقۡنَا ٱلۡإِنسَـٰنَ فِیۤ أَحۡسَنِ تَقۡوِیمࣲ",
      "translation": "Sungguh, Kami telah menciptakan manusia dalam bentuk yang sebaik-baiknya"
    },
    {
      "verse": 5,
      "arabic": "ثُمَّ رَدَدۡنَـٰهُ أَسۡفَلَ سَـٰفِلِینَ",
      "translation": "kemudian Kami kembalikan dia ke tempat yang serendah-rendahnya"
    },
    {
      "verse": 6,
      "arabic": "إِلَّا ٱلَّذِینَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّـٰلِحَـٰتِ فَلَهُمۡ أَجۡرٌ غَیۡرُ مَمۡنُونࣲ",
      "translation": "kecuali orang-orang yang beriman dan mengerjakan kebajikan; maka mereka akan mendapat pahala yang tidak ada putus-putusnya"
    },
    {
      "verse": 7,
      "arabic": "فَمَا یُكَذِّبُكَ بَعۡدُ بِٱلدِّینِ",
      "translation": "Maka apa yang menyebabkan (mereka) mendustakanmu (tentang) hari pembalasan setelah (adanya keterangan-keterangan) itu"
    },
    {
      "verse": 8,
      "arabic": "أَلَیۡسَ ٱللَّهُ بِأَحۡكَمِ ٱلۡحَـٰكِمِینَ",
      "translation": "Bukankah Allah Hakim yang paling adil"
    }
  ],
  "96": [
    {
      "verse": 1,
      "arabic": "ٱقۡرَأۡ بِٱسۡمِ رَبِّكَ ٱلَّذِی خَلَقَ",
      "translation": "Bacalah dengan (menyebut) nama Tuhanmu yang menciptakan"
    },
    {
      "verse": 2,
      "arabic": "خَلَقَ ٱلۡإِنسَـٰنَ مِنۡ عَلَقٍ",
      "translation": "Dia telah menciptakan manusia dari segumpal darah"
    },
    {
      "verse": 3,
      "arabic": "ٱقۡرَأۡ وَرَبُّكَ ٱلۡأَكۡرَمُ",
      "translation": "Bacalah, dan Tuhanmulah Yang Mahamulia"
    },
    {
      "verse": 4,
      "arabic": "ٱلَّذِی عَلَّمَ بِٱلۡقَلَمِ",
      "translation": "Yang mengajar (manusia) dengan pena"
    },
    {
      "verse": 5,
      "arabic": "عَلَّمَ ٱلۡإِنسَـٰنَ مَا لَمۡ یَعۡلَمۡ",
      "translation": "Dia mengajarkan manusia apa yang tidak diketahuinya"
    },
    {
      "verse": 6,
      "arabic": "كَلَّاۤ إِنَّ ٱلۡإِنسَـٰنَ لَیَطۡغَىٰۤ",
      "translation": "Sekali-sekali tidak! Sungguh, manusia itu benar-benar melampaui batas"
    },
    {
      "verse": 7,
      "arabic": "أَن رَّءَاهُ ٱسۡتَغۡنَىٰۤ",
      "translation": "apabila melihat dirinya serba cukup"
    },
    {
      "verse": 8,
      "arabic": "إِنَّ إِلَىٰ رَبِّكَ ٱلرُّجۡعَىٰۤ",
      "translation": "Sungguh, hanya kepada Tuhanmulah tempat kembali(mu)"
    },
    {
      "verse": 9,
      "arabic": "أَرَءَیۡتَ ٱلَّذِی یَنۡهَىٰ",
      "translation": "Bagaimana pendapatmu tentang orang yang melarang"
    },
    {
      "verse": 10,
      "arabic": "عَبۡدًا إِذَا صَلَّىٰۤ",
      "translation": "seorang hamba ketika dia melaksanakan salat"
    },
    {
      "verse": 11,
      "arabic": "أَرَءَیۡتَ إِن كَانَ عَلَى ٱلۡهُدَىٰۤ",
      "translation": "bagaimana pendapatmu jika dia (yang dilarang salat itu) berada di atas kebenaran (petunjuk)"
    },
    {
      "verse": 12,
      "arabic": "أَوۡ أَمَرَ بِٱلتَّقۡوَىٰۤ",
      "translation": "atau dia menyuruh bertakwa (kepada Allah)"
    },
    {
      "verse": 13,
      "arabic": "أَرَءَیۡتَ إِن كَذَّبَ وَتَوَلَّىٰۤ",
      "translation": "Bagaimana pendapatmu jika dia (yang melarang) itu mendustakan dan berpaling"
    },
    {
      "verse": 14,
      "arabic": "أَلَمۡ یَعۡلَم بِأَنَّ ٱللَّهَ یَرَىٰ",
      "translation": "Tidakkah dia mengetahui bahwa sesungguhnya Allah melihat (segala perbuatannya)"
    },
    {
      "verse": 15,
      "arabic": "كَلَّا لَئِن لَّمۡ یَنتَهِ لَنَسۡفَعَۢا بِٱلنَّاصِیَةِ",
      "translation": "Sekali-kali tidak! Sungguh, jika dia tidak berhenti (berbuat demikian) niscaya Kami tarik ubun-ubunnya (ke dalam neraka)"
    },
    {
      "verse": 16,
      "arabic": "نَاصِیَةࣲ كَـٰذِبَةٍ خَاطِئَةࣲ",
      "translation": "(yaitu) ubun-ubun orang yang mendustakan dan durhaka"
    },
    {
      "verse": 17,
      "arabic": "فَلۡیَدۡعُ نَادِیَهُۥ",
      "translation": "Maka biarlah dia memanggil golongannya (untuk menolongnya)"
    },
    {
      "verse": 18,
      "arabic": "سَنَدۡعُ ٱلزَّبَانِیَةَ",
      "translation": "kelak Kami akan memanggil Malaikat Zabaniyah (penyiksa orang-orang yang berdosa)"
    },
    {
      "verse": 19,
      "arabic": "كَلَّا لَا تُطِعۡهُ وَ̅ٱ̅سۡ̅جُ̅دۡ̅ وَٱقۡتَرِب ۩",
      "translation": "sekali-kali tidak! Janganlah kamu patuh kepadanya; dan sujudlah serta dekatkanlah (dirimu kepada Allah)"
    }
  ],
  "97": [
    {
      "verse": 1,
      "arabic": "إِنَّاۤ أَنزَلۡنَـٰهُ فِی لَیۡلَةِ ٱلۡقَدۡرِ",
      "translation": "Sesungguhnya Kami telah menurunkannya (Alquran) pada malam qadar"
    },
    {
      "verse": 2,
      "arabic": "وَمَاۤ أَدۡرَىٰكَ مَا لَیۡلَةُ ٱلۡقَدۡرِ",
      "translation": "Dan tahukah kamu apakah malam kemuliaan itu"
    },
    {
      "verse": 3,
      "arabic": "لَیۡلَةُ ٱلۡقَدۡرِ خَیۡرࣱ مِّنۡ أَلۡفِ شَهۡرࣲ",
      "translation": "Malam kemuliaan itu lebih baik daripada seribu bulan"
    },
    {
      "verse": 4,
      "arabic": "تَنَزَّلُ ٱلۡمَلَـٰۤئِكَةُ وَٱلرُّوحُ فِیهَا بِإِذۡنِ رَبِّهِم مِّن كُلِّ أَمۡرࣲ",
      "translation": "Pada malam itu turun para malaikat dan Ruh (Jibril) dengan izin Tuhannya untuk mengatur semua urusan"
    },
    {
      "verse": 5,
      "arabic": "سَلَـٰمٌ هِیَ حَتَّىٰ مَطۡلَعِ ٱلۡفَجۡرِ",
      "translation": "Sejahteralah (malam itu) sampai terbit fajar"
    }
  ],
  "98": [
    {
      "verse": 1,
      "arabic": "لَمۡ یَكُنِ ٱلَّذِینَ كَفَرُوا۟ مِنۡ أَهۡلِ ٱلۡكِتَـٰبِ وَٱلۡمُشۡرِكِینَ مُنفَكِّینَ حَتَّىٰ تَأۡتِیَهُمُ ٱلۡبَیِّنَةُ",
      "translation": "Orang-orang yang kafir dari golongan Ahli Kitab dan orang-orang musyrik tidak akan meninggalkan (agama mereka) sampai datang kepada mereka bukti yang nyata"
    },
    {
      "verse": 2,
      "arabic": "رَسُولࣱ مِّنَ ٱللَّهِ یَتۡلُوا۟ صُحُفࣰا مُّطَهَّرَةࣰ",
      "translation": "(yaitu) seorang Rasul dari Allah (Muhammad) yang membacakan lembaran-lembaran yang suci (Alquran)"
    },
    {
      "verse": 3,
      "arabic": "فِیهَا كُتُبࣱ قَیِّمَةࣱ",
      "translation": "di dalamnya terdapat (isi) kitab-kitab yang lurus (benar)"
    },
    {
      "verse": 4,
      "arabic": "وَمَا تَفَرَّقَ ٱلَّذِینَ أُوتُوا۟ ٱلۡكِتَـٰبَ إِلَّا مِنۢ بَعۡدِ مَا جَاۤءَتۡهُمُ ٱلۡبَیِّنَةُ",
      "translation": "Dan tidaklah terpecah belah orang-orang Ahli Kitab melainkan setelah datang kepada mereka bukti yang nyata"
    },
    {
      "verse": 5,
      "arabic": "وَمَاۤ أُمِرُوۤا۟ إِلَّا لِیَعۡبُدُوا۟ ٱللَّهَ مُخۡلِصِینَ لَهُ ٱلدِّینَ حُنَفَاۤءَ وَیُقِیمُوا۟ ٱلصَّلَوٰةَ وَیُؤۡتُوا۟ ٱلزَّكَوٰةَۚ وَذَ ٰلِكَ دِینُ ٱلۡقَیِّمَةِ",
      "translation": "Padahal mereka hanya diperintah menyembah Allah dengan ikhlas menaati-Nya semata-mata karena (menjalankan) agama, dan juga agar melaksanakan salat dan menunaikan zakat; dan yang demikian itulah agama yang lurus (benar)"
    },
    {
      "verse": 6,
      "arabic": "إِنَّ ٱلَّذِینَ كَفَرُوا۟ مِنۡ أَهۡلِ ٱلۡكِتَـٰبِ وَٱلۡمُشۡرِكِینَ فِی نَارِ جَهَنَّمَ خَـٰلِدِینَ فِیهَاۤۚ أُو۟لَـٰۤئِكَ هُمۡ شَرُّ ٱلۡبَرِیَّةِ",
      "translation": "Sungguh, orang-orang yang kafir dari golongan Ahli Kitab dan orang-orang musyrik (akan masuk) ke neraka Jahanam; mereka kekal di dalamnya selama-lamanya. Mereka itu adalah sejahat-jahat makhluk"
    },
    {
      "verse": 7,
      "arabic": "إِنَّ ٱلَّذِینَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّـٰلِحَـٰتِ أُو۟لَـٰۤئِكَ هُمۡ خَیۡرُ ٱلۡبَرِیَّةِ",
      "translation": "Sungguh, orang-orang yang beriman dan mengerjakan kebajikan, mereka itulah sebaik-baik makhluk"
    },
    {
      "verse": 8,
      "arabic": "جَزَاۤؤُهُمۡ عِندَ رَبِّهِمۡ جَنَّـٰتُ عَدۡنࣲ تَجۡرِی مِن تَحۡتِهَا ٱلۡأَنۡهَـٰرُ خَـٰلِدِینَ فِیهَاۤ أَبَدࣰاۖ رَّضِیَ ٱللَّهُ عَنۡهُمۡ وَرَضُوا۟ عَنۡهُۚ ذَ ٰلِكَ لِمَنۡ خَشِیَ رَبَّهُۥ",
      "translation": "Balasan mereka di sisi Tuhan mereka ialah surga 'Ādn yang mengalir di bawahnya sungai-sungai; mereka kekal di dalamnya selama-lamanya. Allah rida terhadap mereka dan mereka pun rida kepada-Nya. Yang demikian itu adalah (balasan) bagi orang yang takut kepada Tuhannya"
    }
  ],
  "99": [
    {
      "verse": 1,
      "arabic": "إِذَا زُلۡزِلَتِ ٱلۡأَرۡضُ زِلۡزَالَهَا",
      "translation": "Apabila bumi diguncangkan dengan guncangan yang dahsyat"
    },
    {
      "verse": 2,
      "arabic": "وَأَخۡرَجَتِ ٱلۡأَرۡضُ أَثۡقَالَهَا",
      "translation": "dan bumi telah mengeluarkan beban-beban berat (yang dikandung)nya"
    },
    {
      "verse": 3,
      "arabic": "وَقَالَ ٱلۡإِنسَـٰنُ مَا لَهَا",
      "translation": "dan manusia bertanya, \"Apa yang terjadi pada bumi ini"
    },
    {
      "verse": 4,
      "arabic": "یَوۡمَئِذࣲ تُحَدِّثُ أَخۡبَارَهَا",
      "translation": "Pada hari itu bumi menyampaikan beritanya"
    },
    {
      "verse": 5,
      "arabic": "بِأَنَّ رَبَّكَ أَوۡحَىٰ لَهَا",
      "translation": "karena sesungguhnya Tuhanmu telah memerintahkan (yang sedemikian itu) padanya"
    },
    {
      "verse": 6,
      "arabic": "یَوۡمَئِذࣲ یَصۡدُرُ ٱلنَّاسُ أَشۡتَاتࣰا لِّیُرَوۡا۟ أَعۡمَـٰلَهُمۡ",
      "translation": "(Pada hari itu manusia keluar dari kuburnya dalam keadaan berkelompok-kelompok,922) untuk diperlihatkan kepada mereka (balasan) semua amal perbuatannya"
    },
    {
      "verse": 7,
      "arabic": "فَمَن یَعۡمَلۡ مِثۡقَالَ ذَرَّةٍ خَیۡرࣰا یَرَهُۥ",
      "translation": "Maka barangsiapa mengerjakan kebaikan seberat zarah, niscaya dia akan melihat (balasan)nya"
    },
    {
      "verse": 8,
      "arabic": "وَمَن یَعۡمَلۡ مِثۡقَالَ ذَرَّةࣲ شَرࣰّا یَرَهُۥ",
      "translation": "Dan barangsiapa mengerjakan kejahatan seberat zarah, niscaya dia akan melihat (balasan)nya"
    }
  ],
  "100": [
    {
      "verse": 1,
      "arabic": "وَٱلۡعَـٰدِیَـٰتِ ضَبۡحࣰا",
      "translation": "Demi kuda perang yang berlari kencang terengah-engah"
    },
    {
      "verse": 2,
      "arabic": "فَٱلۡمُورِیَـٰتِ قَدۡحࣰا",
      "translation": "dan kuda yang memercikkan bunga api (dengan pukulan kuku kakinya)"
    },
    {
      "verse": 3,
      "arabic": "فَٱلۡمُغِیرَ ٰتِ صُبۡحࣰا",
      "translation": "dan kuda yang menyerang (dengan tiba-tiba) pada waktu pagi"
    },
    {
      "verse": 4,
      "arabic": "فَأَثَرۡنَ بِهِۦ نَقۡعࣰا",
      "translation": "sehingga menerbangkan debu"
    },
    {
      "verse": 5,
      "arabic": "فَوَسَطۡنَ بِهِۦ جَمۡعًا",
      "translation": "lalu menyerbu ke tengah-tengah kumpulan musuh"
    },
    {
      "verse": 6,
      "arabic": "إِنَّ ٱلۡإِنسَـٰنَ لِرَبِّهِۦ لَكَنُودࣱ",
      "translation": "sungguh, manusia itu sangat ingkar, (tidak bersyukur) kepada Tuhannya"
    },
    {
      "verse": 7,
      "arabic": "وَإِنَّهُۥ عَلَىٰ ذَ ٰلِكَ لَشَهِیدࣱ",
      "translation": "dan sesungguhnya dia (manusia) menyaksikan (mengakui) keingkarannya"
    },
    {
      "verse": 8,
      "arabic": "وَإِنَّهُۥ لِحُبِّ ٱلۡخَیۡرِ لَشَدِیدٌ",
      "translation": "dan sesungguhnya cintanya kepada harta benar-benar berlebihan"
    },
    {
      "verse": 9,
      "arabic": "۞ أَفَلَا یَعۡلَمُ إِذَا بُعۡثِرَ مَا فِی ٱلۡقُبُورِ",
      "translation": "Maka tidakkah dia mengetahui apabila apa yang di dalam kubur dikeluarkan"
    },
    {
      "verse": 10,
      "arabic": "وَحُصِّلَ مَا فِی ٱلصُّدُورِ",
      "translation": "dan apa yang tersimpan di dalam dada dikeluarkan"
    },
    {
      "verse": 11,
      "arabic": "إِنَّ رَبَّهُم بِهِمۡ یَوۡمَئِذࣲ لَّخَبِیرُۢ",
      "translation": "sungguh, Tuhan mereka pada hari itu Mahateliti terhadap keadaan mereka"
    }
  ],
  "101": [
    {
      "verse": 1,
      "arabic": "ٱلۡقَارِعَةُ",
      "translation": "Hari Kiamat"
    },
    {
      "verse": 2,
      "arabic": "مَا ٱلۡقَارِعَةُ",
      "translation": "Apakah hari Kiamat itu"
    },
    {
      "verse": 3,
      "arabic": "وَمَاۤ أَدۡرَىٰكَ مَا ٱلۡقَارِعَةُ",
      "translation": "Dan tahukah kamu apakah hari Kiamat itu"
    },
    {
      "verse": 4,
      "arabic": "یَوۡمَ یَكُونُ ٱلنَّاسُ كَٱلۡفَرَاشِ ٱلۡمَبۡثُوثِ",
      "translation": "Pada hari itu manusia seperti laron yang beterbangan"
    },
    {
      "verse": 5,
      "arabic": "وَتَكُونُ ٱلۡجِبَالُ كَٱلۡعِهۡنِ ٱلۡمَنفُوشِ",
      "translation": "dan gunung-gunung seperti bulu yang dihambur-hamburkan"
    },
    {
      "verse": 6,
      "arabic": "فَأَمَّا مَن ثَقُلَتۡ مَوَ ٰزِینُهُۥ",
      "translation": "Maka adapun orang yang berat timbangan (kebaikan)nya"
    },
    {
      "verse": 7,
      "arabic": "فَهُوَ فِی عِیشَةࣲ رَّاضِیَةࣲ",
      "translation": "maka dia berada dalam kehidupan yang memuaskan (senang)"
    },
    {
      "verse": 8,
      "arabic": "وَأَمَّا مَنۡ خَفَّتۡ مَوَ ٰزِینُهُۥ",
      "translation": "Dan adapun orang yang ringan timbangan (kebaikan)nya"
    },
    {
      "verse": 9,
      "arabic": "فَأُمُّهُۥ هَاوِیَةࣱ",
      "translation": "maka tempat kembalinya adalah neraka Hāwiyah"
    },
    {
      "verse": 10,
      "arabic": "وَمَاۤ أَدۡرَىٰكَ مَا هِیَهۡ",
      "translation": "Dan tahukah kamu apakah neraka Hāwiyah itu"
    },
    {
      "verse": 11,
      "arabic": "نَارٌ حَامِیَةُۢ",
      "translation": "(Yaitu) api yang sangat panas"
    }
  ],
  "102": [
    {
      "verse": 1,
      "arabic": "أَلۡهَىٰكُمُ ٱلتَّكَاثُرُ",
      "translation": "Bermegah-megahan telah melalaikan kamu"
    },
    {
      "verse": 2,
      "arabic": "حَتَّىٰ زُرۡتُمُ ٱلۡمَقَابِرَ",
      "translation": "sampai kamu masuk ke dalam kubur"
    },
    {
      "verse": 3,
      "arabic": "كَلَّا سَوۡفَ تَعۡلَمُونَ",
      "translation": "Sekali-kali tidak! Kelak kamu akan mengetahui (akibat perbuatanmu itu)"
    },
    {
      "verse": 4,
      "arabic": "ثُمَّ كَلَّا سَوۡفَ تَعۡلَمُونَ",
      "translation": "kemudian sekali-kali tidak! Kelak kamu akan mengetahui"
    },
    {
      "verse": 5,
      "arabic": "كَلَّا لَوۡ تَعۡلَمُونَ عِلۡمَ ٱلۡیَقِینِ",
      "translation": "Sekali-kali tidak! Sekiranya kamu mengetahui dengan pasti"
    },
    {
      "verse": 6,
      "arabic": "لَتَرَوُنَّ ٱلۡجَحِیمَ",
      "translation": "niscaya kamu benar-benar akan melihat neraka Jahim"
    },
    {
      "verse": 7,
      "arabic": "ثُمَّ لَتَرَوُنَّهَا عَیۡنَ ٱلۡیَقِینِ",
      "translation": "kemudian kamu benar-benar akan melihatnya dengan mata kepala sendiri"
    },
    {
      "verse": 8,
      "arabic": "ثُمَّ لَتُسۡءَلُنَّ یَوۡمَئِذٍ عَنِ ٱلنَّعِیمِ",
      "translation": "kemudian kamu benar-benar akan ditanya pada hari itu tentang kenikmatan (yang megah di dunia itu)"
    }
  ],
  "103": [
    {
      "verse": 1,
      "arabic": "وَٱلۡعَصۡرِ",
      "translation": "Demi masa"
    },
    {
      "verse": 2,
      "arabic": "إِنَّ ٱلۡإِنسَـٰنَ لَفِی خُسۡرٍ",
      "translation": "Sungguh, manusia berada dalam kerugian"
    },
    {
      "verse": 3,
      "arabic": "إِلَّا ٱلَّذِینَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّـٰلِحَـٰتِ وَتَوَاصَوۡا۟ بِٱلۡحَقِّ وَتَوَاصَوۡا۟ بِٱلصَّبۡرِ",
      "translation": "kecuali orang-orang yang beriman dan mengerjakan kebajikan serta saling menasihati untuk kebenaran dan saling menasihati untuk kesabaran"
    }
  ],
  "104": [
    {
      "verse": 1,
      "arabic": "وَیۡلࣱ لِّكُلِّ هُمَزَةࣲ لُّمَزَةٍ",
      "translation": "Celakalah bagi setiap pengumpat dan pencela"
    },
    {
      "verse": 2,
      "arabic": "ٱلَّذِی جَمَعَ مَالࣰا وَعَدَّدَهُۥ",
      "translation": "yang mengumpulkan harta dan menghitung-hitungnya"
    },
    {
      "verse": 3,
      "arabic": "یَحۡسَبُ أَنَّ مَالَهُۥۤ أَخۡلَدَهُۥ",
      "translation": "dia (manusia) mengira bahwa hartanya itu dapat mengekalkannya"
    },
    {
      "verse": 4,
      "arabic": "كَلَّاۖ لَیُنۢبَذَنَّ فِی ٱلۡحُطَمَةِ",
      "translation": "Sekali-kali tidak! Pasti dia akan dilemparkan ke dalam (neraka) Ḥuṭamah"
    },
    {
      "verse": 5,
      "arabic": "وَمَاۤ أَدۡرَىٰكَ مَا ٱلۡحُطَمَةُ",
      "translation": "Dan tahukah kamu apakah (neraka) Ḥuṭamah itu"
    },
    {
      "verse": 6,
      "arabic": "نَارُ ٱللَّهِ ٱلۡمُوقَدَةُ",
      "translation": "(Yaitu) api (azab) Allah yang dinyalakan"
    },
    {
      "verse": 7,
      "arabic": "ٱلَّتِی تَطَّلِعُ عَلَى ٱلۡأَفۡءِدَةِ",
      "translation": "yang (membakar) sampai ke hati"
    },
    {
      "verse": 8,
      "arabic": "إِنَّهَا عَلَیۡهِم مُّؤۡصَدَةࣱ",
      "translation": "Sungguh, api itu ditutup rapat atas (diri) mereka"
    },
    {
      "verse": 9,
      "arabic": "فِی عَمَدࣲ مُّمَدَّدَةِۭ",
      "translation": "(sedang mereka itu) diikat pada tiang-tiang yang panjang"
    }
  ],
  "105": [
    {
      "verse": 1,
      "arabic": "أَلَمۡ تَرَ كَیۡفَ فَعَلَ رَبُّكَ بِأَصۡحَـٰبِ ٱلۡفِیلِ",
      "translation": "Tidakkah engkau (Muhammad) perhatikan bagaimana Tuhanmu telah bertindak terhadap pasukan bergajah"
    },
    {
      "verse": 2,
      "arabic": "أَلَمۡ یَجۡعَلۡ كَیۡدَهُمۡ فِی تَضۡلِیلࣲ",
      "translation": "Bukankah Dia telah menjadikan tipu daya mereka itu sia-sia"
    },
    {
      "verse": 3,
      "arabic": "وَأَرۡسَلَ عَلَیۡهِمۡ طَیۡرًا أَبَابِیلَ",
      "translation": "dan Dia mengirimkan kepada mereka burung yang berbondong-bondong"
    },
    {
      "verse": 4,
      "arabic": "تَرۡمِیهِم بِحِجَارَةࣲ مِّن سِجِّیلࣲ",
      "translation": "yang melempari mereka dengan batu dari tanah liat yang dibakar"
    },
    {
      "verse": 5,
      "arabic": "فَجَعَلَهُمۡ كَعَصۡفࣲ مَّأۡكُولِۭ",
      "translation": "sehingga mereka dijadikan-Nya seperti daun-daun yang dimakan (ulat)"
    }
  ],
  "106": [
    {
      "verse": 1,
      "arabic": "لِإِیلَـٰفِ قُرَیۡشٍ",
      "translation": "Karena kebiasaan orang-orang Quraisy"
    },
    {
      "verse": 2,
      "arabic": "إِۦلَـٰفِهِمۡ رِحۡلَةَ ٱلشِّتَاۤءِ وَٱلصَّیۡفِ",
      "translation": "(yaitu) kebiasaan mereka bepergian pada musim dingin dan musim panas"
    },
    {
      "verse": 3,
      "arabic": "فَلۡیَعۡبُدُوا۟ رَبَّ هَـٰذَا ٱلۡبَیۡتِ",
      "translation": "Maka hendaklah mereka menyembah Tuhan (pemilik) rumah ini (Ka'bah)"
    },
    {
      "verse": 4,
      "arabic": "ٱلَّذِیۤ أَطۡعَمَهُم مِّن جُوعࣲ وَءَامَنَهُم مِّنۡ خَوۡفِۭ",
      "translation": "yang telah memberi makanan kepada mereka untuk menghilangkan lapar dan mengamankan mereka dari rasa ketakutan"
    }
  ],
  "107": [
    {
      "verse": 1,
      "arabic": "أَرَءَیۡتَ ٱلَّذِی یُكَذِّبُ بِٱلدِّینِ",
      "translation": "Tahukah kamu (orang) yang mendustakan agama"
    },
    {
      "verse": 2,
      "arabic": "فَذَ ٰلِكَ ٱلَّذِی یَدُعُّ ٱلۡیَتِیمَ",
      "translation": "Maka itulah orang yang menghardik anak yatim"
    },
    {
      "verse": 3,
      "arabic": "وَلَا یَحُضُّ عَلَىٰ طَعَامِ ٱلۡمِسۡكِینِ",
      "translation": "dan tidak mengajak memberi makan orang miskin"
    },
    {
      "verse": 4,
      "arabic": "فَوَیۡلࣱ لِّلۡمُصَلِّینَ",
      "translation": "Maka celakalah orang yang salat"
    },
    {
      "verse": 5,
      "arabic": "ٱلَّذِینَ هُمۡ عَن صَلَاتِهِمۡ سَاهُونَ",
      "translation": "(yaitu) orang-orang yang lalai terhadap salatnya"
    },
    {
      "verse": 6,
      "arabic": "ٱلَّذِینَ هُمۡ یُرَاۤءُونَ",
      "translation": "yang berbuat riya"
    },
    {
      "verse": 7,
      "arabic": "وَیَمۡنَعُونَ ٱلۡمَاعُونَ",
      "translation": "dan enggan (memberikan) bantuan"
    }
  ],
  "108": [
    {
      "verse": 1,
      "arabic": "إِنَّاۤ أَعۡطَیۡنَـٰكَ ٱلۡكَوۡثَرَ",
      "translation": "Sungguh, Kami telah memberimu (Muhammad) nikmat yang banyak"
    },
    {
      "verse": 2,
      "arabic": "فَصَلِّ لِرَبِّكَ وَٱنۡحَرۡ",
      "translation": "Maka laksanakanlah salat karena Tuhanmu, dan berkurbanlah (sebagai ibadah dan mendekatkan diri kepada Allah)"
    },
    {
      "verse": 3,
      "arabic": "إِنَّ شَانِئَكَ هُوَ ٱلۡأَبۡتَرُ",
      "translation": "Sungguh, orang-orang yang membencimu dialah yang terputus (dari rahmat Allah)"
    }
  ],
  "109": [
    {
      "verse": 1,
      "arabic": "قُلۡ یَـٰۤأَیُّهَا ٱلۡكَـٰفِرُونَ",
      "translation": "Katakanlah (Muhammad), \"Wahai orang-orang kafir"
    },
    {
      "verse": 2,
      "arabic": "لَاۤ أَعۡبُدُ مَا تَعۡبُدُونَ",
      "translation": "aku tidak akan menyembah apa yang kamu sembah"
    },
    {
      "verse": 3,
      "arabic": "وَلَاۤ أَنتُمۡ عَـٰبِدُونَ مَاۤ أَعۡبُدُ",
      "translation": "dan kamu bukan penyembah apa yang aku sembah"
    },
    {
      "verse": 4,
      "arabic": "وَلَاۤ أَنَا۠ عَابِدࣱ مَّا عَبَدتُّمۡ",
      "translation": "dan aku tidak pernah menjadi penyembah apa yang kamu sembah"
    },
    {
      "verse": 5,
      "arabic": "وَلَاۤ أَنتُمۡ عَـٰبِدُونَ مَاۤ أَعۡبُدُ",
      "translation": "dan kamu tidak pernah (pula) menjadi penyembah apa yang aku sembah"
    },
    {
      "verse": 6,
      "arabic": "لَكُمۡ دِینُكُمۡ وَلِیَ دِینِ",
      "translation": "Untukmu agamamu, dan untukku agamaku"
    }
  ],
  "110": [
    {
      "verse": 1,
      "arabic": "إِذَا جَاۤءَ نَصۡرُ ٱللَّهِ وَٱلۡفَتۡحُ",
      "translation": "Apabila telah datang pertolongan Allah dan kemenangan"
    },
    {
      "verse": 2,
      "arabic": "وَرَأَیۡتَ ٱلنَّاسَ یَدۡخُلُونَ فِی دِینِ ٱللَّهِ أَفۡوَاجࣰا",
      "translation": "dan engkau melihat manusia berbondong-bondong masuk agama Allah"
    },
    {
      "verse": 3,
      "arabic": "فَسَبِّحۡ بِحَمۡدِ رَبِّكَ وَٱسۡتَغۡفِرۡهُۚ إِنَّهُۥ كَانَ تَوَّابَۢا",
      "translation": "maka bertasbihlah dengan memuji Tuhanmu dan mohonlah ampunan kepada-Nya. Sungguh, Dia Maha Penerima tobat"
    }
  ],
  "111": [
    {
      "verse": 1,
      "arabic": "تَبَّتۡ یَدَاۤ أَبِی لَهَبࣲ وَتَبَّ",
      "translation": "Binasalah kedua tangan Abu Lahab dan benar-benar binasa dia"
    },
    {
      "verse": 2,
      "arabic": "مَاۤ أَغۡنَىٰ عَنۡهُ مَالُهُۥ وَمَا كَسَبَ",
      "translation": "Tidaklah berguna baginya hartanya dan apa yang dia usahakan"
    },
    {
      "verse": 3,
      "arabic": "سَیَصۡلَىٰ نَارࣰا ذَاتَ لَهَبࣲ",
      "translation": "Kelak dia akan masuk ke dalam api yang bergejolak (neraka)"
    },
    {
      "verse": 4,
      "arabic": "وَٱمۡرَأَتُهُۥ حَمَّالَةَ ٱلۡحَطَبِ",
      "translation": "Dan (begitu pula) istrinya, pembawa kayu bakar (penyebar fitnah)"
    },
    {
      "verse": 5,
      "arabic": "فِی جِیدِهَا حَبۡلࣱ مِّن مَّسَدِۭ",
      "translation": "Di lehernya ada tali dari sabut yang dipintal"
    }
  ],
  "112": [
    {
      "verse": 1,
      "arabic": "قُلۡ هُوَ ٱللَّهُ أَحَدٌ",
      "translation": "Katakanlah (Muhammad), \"Dialah Allah, Yang Maha Esa"
    },
    {
      "verse": 2,
      "arabic": "ٱللَّهُ ٱلصَّمَدُ",
      "translation": "Allah tempat meminta segala sesuatu"
    },
    {
      "verse": 3,
      "arabic": "لَمۡ یَلِدۡ وَلَمۡ یُولَدۡ",
      "translation": "(Allah) tidak beranak dan tidak pula diperanakkan"
    },
    {
      "verse": 4,
      "arabic": "وَلَمۡ یَكُن لَّهُۥ كُفُوًا أَحَدُۢ",
      "translation": "Dan tidak ada sesuatu yang setara dengan Dia"
    }
  ],
  "113": [
    {
      "verse": 1,
      "arabic": "قُلۡ أَعُوذُ بِرَبِّ ٱلۡفَلَقِ",
      "translation": "Katakanlah, \"Aku berlindung kepada Tuhan yang menguasai subuh (fajar)"
    },
    {
      "verse": 2,
      "arabic": "مِن شَرِّ مَا خَلَقَ",
      "translation": "dari kejahatan (makhluk yang) Dia ciptakan"
    },
    {
      "verse": 3,
      "arabic": "وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ",
      "translation": "dan dari kejahatan malam apabila telah gelap gulita"
    },
    {
      "verse": 4,
      "arabic": "وَمِن شَرِّ ٱلنَّفَّـٰثَـٰتِ فِی ٱلۡعُقَدِ",
      "translation": "dan dari kejahatan (perempuan-perempuan) penyihir yang meniup pada buhul-buhul (talinya)"
    },
    {
      "verse": 5,
      "arabic": "وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
      "translation": "dan dari kejahatan orang yang dengki apabila dia dengki"
    }
  ],
  "114": [
    {
      "verse": 1,
      "arabic": "قُلۡ أَعُوذُ بِرَبِّ ٱلنَّاسِ",
      "translation": "Katakanlah, \"Aku berlindung kepada Tuhannya manusia"
    },
    {
      "verse": 2,
      "arabic": "مَلِكِ ٱلنَّاسِ",
      "translation": "Raja manusia"
    },
    {
      "verse": 3,
      "arabic": "إِلَـٰهِ ٱلنَّاسِ",
      "translation": "sembahan manusia"
    },
    {
      "verse": 4,
      "arabic": "مِن شَرِّ ٱلۡوَسۡوَاسِ ٱلۡخَنَّاسِ",
      "translation": "dari kejahatan (bisikan) setan yang bersembunyi"
    },
    {
      "verse": 5,
      "arabic": "ٱلَّذِی یُوَسۡوِسُ فِی صُدُورِ ٱلنَّاسِ",
      "translation": "yang membisikkan (kejahatan) ke dalam dada manusia"
    },
    {
      "verse": 6,
      "arabic": "مِنَ ٱلۡجِنَّةِ وَٱلنَّاسِ",
      "translation": "dari (golongan) jin dan manusia"
    }
  ]
};

export const JUZ30_NUMBERS: number[] = [
  78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
];
